// Activity: the audit log, read in the console (src/routes/ops/activity.ts). The design draws no board for it; these
// words are ours.

// The schema's own type, not ../api.ts's: content is read by tests in Node, where the API client's DOM types are not.
import type { components } from "../api-schema.ts";

type ActivityAction = components["schemas"]["ActivityEntry"]["action"];

/** What each action in the log was, as a line in the list says it. */
const ACTIONS: Readonly<Record<ActivityAction, string>> = {
  "ops.call": "Console call",
  "client.call": "Client app call",
  "tech.call": "Technician app call",
  "consent.switch": "Consent changed",
  "number_change.request": "Number change asked for",
  "number_change.withdraw": "Number change withdrawn",
  "number_change.decide": "Number change decided",
  "deletion.request": "Deletion asked for",
  "deletion.decide": "Deletion decided",
  "person.erase": "Client erased",
  "referral.decide": "Referral reward decided",
  "referral.attach": "Invite attached",
  "photo.view": "Photographs opened",
  "pincode.launch": "Pincode launched",
  "data.export": "Data exported",
  "grievance.raise": "Concern raised",
  "grievance.resolve": "Concern answered",
  "no_show.decide": "No-show ruled on",
  "technician_device.revoke": "Phone revoked",
  "technician.allow_sign_in": "Sign-in allowed again",
  "no_show.dispute": "No-show charge disputed",
  "no_show.dispute_rule": "Dispute ruled on",
  "technician.leave": "Leave recorded",
  "technician.leave_cancelled": "Leave cancelled",
  "technician.add": "Technician added",
  "technician.change": "Technician changed",
  "technician.deactivate": "Technician switched off",
  "technician.delete": "Technician deleted",
  "technician.reactivate": "Technician switched on",
  "setting.change": "Setting changed",
  "price.set": "Price set",
  "price.withdraw": "Price withdrawn",
  "slot_times.set": "Slot times set",
  "pincode.set": "Pincode served or paused",
  "pincode.rename": "Area renamed",
  "pincode.add": "Pincode added",
  "blackout.add": "Blackout day added",
  "blackout.remove": "Blackout day removed",
  "service.add": "Service added",
  "service.rename": "Service renamed",
  "service.describe": "Service described",
  "service.length": "Service length changed",
  "service.reorder": "Services reordered",
  "service.retire": "Service retired",
  "service.restore": "Service offered again",
  "credit.adjust": "Credits adjusted",
  "dispatch.client_told": "Client told of a move",
  "dispatch.check_in_cleared": "Check-in cleared by a move",
  "consumable.add": "Consumable added",
  "consumable.change": "Consumable changed",
  "consumable.retire": "Consumable retired",
  "consumable.delete": "Consumable deleted",
  "consumable.restore": "Consumable restored",
  "consumable.usage": "Usage set",
  "job_sheet.set": "Job sheet set",
  "stock.receive": "Stock received",
  "stock.transfer": "Stock moved",
  "stock.count": "Stock counted",
  "stock.write_off": "Stock written off",
  "task.assign": "Task taken or given",
  "task.hand_back": "Task handed back",
  "task.close": "Task closed",
  "address.given_to_ops": "Address taken by phone",
  "alert.resolve": "Alert marked done",
  "alert.send_again": "Alert sent again",
  "booking.give_back": "Hold let go",
  "visit.book": "Visit booked",
  "visit.cancel": "Visit cancelled",
  "visit.close": "Visit closed by hand",
  "visit.checkin_waive": "Check-in waived",
  "hair_profile.correct": "Hair profile corrected",
  "discount_code.make": "Discount codes made",
  "discount_code.switch_off": "Discount code switched off",
  "discount_code.delete": "Discount code deleted",
  "discount_code.apply": "Discount code applied",
  "discount_code.remove": "Discount code taken off",
  "staff.set": "Staff access changed",
  "staff.enforce": "Staff list enforced",
  "staff.token_add": "Service token let in",
  "staff.token_remove": "Service token taken off",
  "staff.delete": "Staff member removed",
};

export const activity = {
  title: "Activity",
  actions: ACTIONS,
  filters: {
    label: "Narrow the log",
    kind: "Who",
    kinds: {
      any: "Anyone",
      staff: "Staff",
      service: "Service token",
      client: "Client",
      technician: "Technician",
      system: "System",
    },
    actor: "Email or ID",
    action: "What",
    anyAction: "Any action",
    /** A filter a link set, above the form: "Client · Rohit Malhotra", with its own way off. */
    person: "Client",
    visit: "Visit",
    remove: (filter: string) => `Remove filter: ${filter}`,
    from: "From",
    to: "To",
    show: "Show",
    clear: "Clear",
  },
  columns: { when: "When", who: "Who", what: "What", record: "Record" },
  surfaces: { public: "Site", client: "Client app", ops: "Console", tech: "Technician app" },
  /** A client the log names only by ID: erased, or never named. */
  unnamedClient: "Client",
  /** The kind of record an entry names, where the console has a page for it. */
  records: { person: "Client", appointment: "Visit" } as Readonly<Record<string, string>>,
  empty: "Nothing in the log matches.",
  older: "Show older",
  loadingOlder: "Loading older…",
};
