/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment, version and database reachability */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                /** @description The database is unreachable or belongs to another environment */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find a client by mobile number. A POST, so the number stays out of the URL */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientSearch"];
                };
            };
            responses: {
                /** @description The client, to open their page with */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            mobile: string;
                        };
                    };
                };
                /** @description invalid_request: not an Indian mobile number */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such client, or the client has been erased */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The client's record: who they are, their address, their visits, their payments and their history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientRecord"];
                    };
                };
                /** @description not_found: no such client, or the client has been erased */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which photographs the client has, by visit, newest first. No image is served here */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Visits that have photographs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientPhotos"];
                    };
                };
                /** @description not_found: no such client, or the client has been erased */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of the client's photographs. The audit entry is written before the image is */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    photo_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                        "image/png": string;
                    };
                };
                /** @description not_found: no such photograph of this client's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unavailable: the view could not be audited, so no photograph is served */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The client's consents and any deletion request. Ops read them and never grant one */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Consents and data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientConsents"];
                    };
                };
                /** @description not_found: no such client, or the client has been erased */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/number-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Number changes waiting for ops: both numbers proven by code */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Oldest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            changes: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                person_id: string;
                                name: string;
                                old_mobile: string;
                                new_mobile: string;
                                /** Format: date-time */
                                requested_at: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/number-changes/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a number change, which then takes effect, or reject it */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NumberChangeDecision"];
                };
            };
            responses: {
                /** @description Decided */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            state: "confirmed" | "rejected";
                        };
                    };
                };
                /** @description invalid_request: a rejection needs a reason */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no change waiting for ops by that ID */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description number_in_use: another person holds the new number */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deletion-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deletion requests waiting for ops */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Oldest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            requests: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                person_id: string;
                                name: string;
                                mobile: string;
                                /** Format: date-time */
                                requested_at: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deletion-requests/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete the account now (photographs, results and details), or reject the request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeletionDecision"];
                };
            };
            responses: {
                /** @description Decided */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            state: "done" | "rejected";
                        };
                    };
                };
                /** @description invalid_request: a rejection needs a reason */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no request waiting for ops by that ID */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description visit_booked or payment_held: cancel the visits and refund the payments it names first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErasureRefused"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/referrals/held": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Referral grants held for review, oldest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Held grants */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            held: {
                                /** Format: uuid */
                                id: string;
                                referrer: {
                                    /** Format: uuid */
                                    person_id: string;
                                    name: string;
                                };
                                referred: {
                                    /** Format: uuid */
                                    person_id: string;
                                    name: string;
                                };
                                /** Format: date */
                                fitted_on: string;
                                signals: ("shared_address" | "shared_upi" | "monthly_cap" | "same_mobile")[];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/referrals/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a held grant, or reject it */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReferralDecision"];
                };
            };
            responses: {
                /** @description Decided */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            state: "approved" | "rejected";
                        };
                    };
                };
                /** @description invalid_request: a rejection needs a reason */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no held grant by that ID */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grievances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open grievances, oldest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Open grievances */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            grievances: {
                                /** Format: uuid */
                                id: string;
                                person_id: string;
                                name: string;
                                mobile: string;
                                text: string;
                                /** Format: date-time */
                                raised_at: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grievances/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record ops' answer to a grievance, and close it */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GrievanceAnswer"];
                };
            };
            responses: {
                /** @description Closed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            state: "resolved";
                        };
                    };
                };
                /** @description not_found: no open grievance by that ID */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is waiting, by pincode, the longest wait first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Areas with someone waiting */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            areas: {
                                pincode: string;
                                area: string | null;
                                city: string | null;
                                served: boolean;
                                launched_at: string | null;
                                waiting: number;
                                oldest: string | null;
                                referred: number;
                                /** @description How many asked to be told when we launch. */
                                alerts: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pincodes/{pin}/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch a pincode: without confirm, what it would send; with it, the launch */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pin: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PincodeLaunch"];
                };
            };
            responses: {
                /** @description What it would send, or what it sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pincode: string;
                            waiting: number;
                            alerts: number;
                            launched: boolean;
                        };
                    };
                };
                /** @description not_found: we have no such pincode */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/referrers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every referrer's figures, the busiest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Referrers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            referrers: {
                                code: string;
                                name: string;
                                opens: number;
                                consultations: number;
                                fits: number;
                                granted: number;
                                /** @description Credits of theirs spent on visits. */
                                redeemed: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The dispatch board: seven days of every active technician, with the unassigned tray */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    city?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The board */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DispatchBoard"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dispatch/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Put a job on a technician, with a reason. The clash check runs before any write to FSM */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DispatchAssignRequest"];
                };
            };
            responses: {
                /** @description Assigned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DispatchMoved"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such live job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description clash: the technician already holds a job in that window on that date; on_leave: they are away that day */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description fsm_refused: FSM would not take it; nothing moved */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dispatch/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a job to another technician, day or window, with a reason. The client is never charged */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DispatchMoveRequest"];
                };
            };
            responses: {
                /** @description Moved, and the client told */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DispatchMoved"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such live job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description clash; on_leave */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description fsm_refused */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/no-shows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** No-show cases: undecided first, each with its three facts */
        get: {
            parameters: {
                query?: {
                    decision?: "undecided" | "charged" | "waived" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The cases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoShowCases"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/no-shows/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Charge or waive a no-show, from the evidence */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NoShowDecisionRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            decided: boolean;
                        };
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such case, or it was ruled on already */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}/pieces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A client's pieces: code, base, fitted date, supplier lot, replacement due and any failure */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The pieces, newest fit first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientPieces"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such client */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active technicians, the phones they have logged in on, and the leave they are down for */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The technicians */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Technicians"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record leave. Those days are then refused to booking and to the dispatch board alike */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianLeaveRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                        };
                    };
                };
                /** @description invalid_request: to is before from, or more than 365 days ahead */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such active technician */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{id}/leave/{leave}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take leave back, so those days can be worked again */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    leave: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cancelled: boolean;
                        };
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such leave of that technician's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/{id}/devices/{device}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a phone. Its session ends, and it drops its cached jobs on its next contact */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    device: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            revoked_at: string;
                        };
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such phone of that technician's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What ops still have to do, by group, the longest wait first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The groups with something in them */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tasks"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A day's money: what was collected, what went back, and each charge kept or ruled on */
        get: {
            parameters: {
                query?: {
                    /** @description India's calendar date; today when it is left out. */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The day */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsDayMoney"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per technician: jobs finished over a period, and how they ran against the planned length */
        get: {
            parameters: {
                query?: {
                    /** @description India's calendar date the count starts on; 90 days back when it is left out. */
                    from?: string;
                    /** @description Exclusive; tomorrow when it is left out. */
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The technicians */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechniciansWork"];
                    };
                };
                /** @description invalid_request: from is not before to */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every business rule ops may change, with its unit, its bounds and who last set it */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The rules */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            settings: components["schemas"]["OpsSetting"][];
                        };
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set one rule, or send a null value to put the committed default back */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: "checkin_radius_m" | "no_show_wait_min" | "address_unlock_hour" | "task_sla_hours" | "piece_cycle_days";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingChange"];
                };
            };
            responses: {
                /** @description What it is now */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsSetting"];
                    };
                };
                /** @description invalid_request: the figure is outside what the rule allows, and fields names it */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The price book: every price, past, present and scheduled */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prices */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            prices: components["schemas"]["Price"][];
                            /** Format: date */
                            today: string;
                            max_amount_ex_gst: number;
                            max_gst_percent: number;
                        };
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** A price from the date it applies. A change is a new row, so nothing already invoiced moves */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PriceChange"];
                };
            };
            responses: {
                /** @description The book as it now stands */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            prices: components["schemas"]["Price"][];
                        };
                    };
                };
                /** @description invalid_request: fields names what was refused */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service-area": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every pincode we hold, its city, and whether a technician goes there */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pincodes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pincodes: components["schemas"]["ServedPincode"][];
                        };
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Which pincodes we go to, and from when. Only the pincodes named change */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceAreaChange"];
                };
            };
            responses: {
                /** @description What changed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            changed: number;
                            served: number;
                        };
                    };
                };
                /** @description invalid_request: fields names a pincode we do not hold. no_service_area: it would leave none served */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description access_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "not_found" | "invalid_request" | "turnstile_failed" | "rate_limited" | "idempotency_in_progress" | "idempotency_key_reused" | "environment_mismatch" | "unavailable" | "internal_error" | "busy" | "photo_invalid_file" | "upload_already_received" | "upload_missing" | "session_required" | "job_not_claimable" | "look_limit_reached" | "unauthorized" | "visit_booked" | "payment_held" | "forbidden_origin" | "access_required" | "code_expired" | "too_early" | "number_in_use" | "not_ready" | "ops_assisted" | "taken" | "not_bookable" | "hold_expired" | "not_changeable" | "terms_changed" | "consent_required" | "device_revoked" | "superseded" | "out_of_order" | "not_today" | "already_started" | "clash" | "on_leave" | "fsm_refused" | "too_early_to_close" | "no_service_area";
                request_id: string;
                /** @description invalid_request only: the fields that failed validation, never their values. */
                fields?: string[];
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @enum {string} */
            environment: "local" | "staging" | "production";
            /** @description Cloudflare Worker version ID serving this request. */
            version_id: string;
            /** @description Tag given at upload: the git commit SHA in remote environments. */
            version_tag: string | null;
            /**
             * @description ok: reachable and marked as this environment's database. unmarked: no identity row. mismatch: marked as another environment's database.
             * @enum {string}
             */
            d1: "ok" | "unmarked" | "mismatch" | "unreachable";
        };
        ClientSearch: {
            mobile: string;
        };
        ClientRecord: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description E.164, as ops need it to call or message. */
            mobile: string;
            /** @enum {string} */
            state: "fitted" | "lead" | "nothing_booked";
            /**
             * Format: date-time
             * @description When the person's record was first written.
             */
            known_since: string;
            /** @description The address visits go to now. */
            address: components["schemas"]["ClientAddress"] | null;
            /** @description Service visits left and when the soonest expires; null with none left. */
            credits: {
                visits: number;
                /** Format: date-time */
                earliest_expiry: string | null;
            } | null;
            /** @description Upcoming soonest first; past newest first. */
            visits: {
                upcoming: components["schemas"]["ClientVisit"][];
                past: components["schemas"]["ClientVisit"][];
            };
            /** @description Payments and refunds as one list, newest first. */
            payments: (components["schemas"]["PaymentEntry"] | components["schemas"]["RefundEntry"])[];
            history: components["schemas"]["ClientRecordHistory"];
        };
        ClientAddress: {
            line1: string;
            line2: string | null;
            locality: string;
            city: string;
            pincode: string;
            /** @description For the technician: gate code, parking and the like. */
            access_notes: string | null;
        };
        ClientVisit: components["schemas"]["VisitSummary"] & {
            /** @description What FSM closed the visit as; null until it is closed. */
            outcome: ("done" | "partial") | null;
        };
        /** @description Display name and initials only. */
        Technician: {
            name: string;
            initials: string;
        };
        VisitSummary: {
            /** Format: uuid */
            id: string;
            /**
             * Format: date
             * @description India's calendar date.
             */
            date: string;
            /** @enum {string} */
            window_label: "morning" | "afternoon" | "evening";
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            length_minutes: number;
            type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            /** @enum {string} */
            status: "scheduled" | "dispatched" | "in_progress" | "completed" | "cancelled" | "terminated" | "other";
            technician: components["schemas"]["Technician"] | null;
            /** @description The saved address's area, city and pincode, else FSM's city and pincode. */
            place: string;
        };
        PaymentEntry: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "payment";
            /** Format: uuid */
            id: string;
            /**
             * Format: date
             * @description India's calendar date it was made.
             */
            date: string;
            /** @description In paise, GST included. */
            amount: number;
            /** @description In paise, before GST: the main figure. */
            amount_ex_gst: number;
            /** @description The GST rate the amount includes. */
            gst_percent: number;
            /** @description The visit it paid for, when known. */
            visit: {
                /** Format: uuid */
                id: string;
                /** Format: date */
                date: string;
                type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            } | null;
            /** @enum {string} */
            status: "authorized" | "captured" | "refunded" | "partially_refunded";
            /** @description upi, card, netbanking and so on. */
            method: string | null;
            /** @description Ours, e.g. MM-2026-0841, once captured. */
            reference: string | null;
            /** @description In paise: refunds Razorpay has processed. */
            refunded_amount: number;
            /**
             * @description What it paid for: the visit, or a late fee.
             * @enum {string}
             */
            purpose: "visit" | "late_fee";
            /** @description Kept under the 24-hour rule, with its evidence: "cancelled 9:14 am, visit was 10 am". */
            charge: {
                /** @enum {string} */
                change: "cancelled" | "moved";
                /**
                 * Format: date-time
                 * @description When the client cancelled or moved the visit.
                 */
                at: string;
                /**
                 * Format: date-time
                 * @description When the visit was to start.
                 */
                visit_started_at: string;
                /** @description In paise: what was kept. */
                amount: number;
            } | null;
        };
        RefundEntry: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "refund";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            payment_id: string;
            /**
             * Format: date
             * @description India's calendar date it was made.
             */
            date: string;
            /** @description In paise, GST included. */
            amount: number;
            /** @description In paise, before GST: the main figure. */
            amount_ex_gst: number;
            /** @description The GST rate the amount includes. */
            gst_percent: number;
            /** @description The visit it paid for, when known. */
            visit: {
                /** Format: uuid */
                id: string;
                /** Format: date */
                date: string;
                type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            } | null;
            /** @enum {string} */
            status: "created" | "processed" | "failed";
            /** @description Where the money goes back to: the payment's method. */
            destination: string | null;
            /** @description normal (5 to 7 working days) or instant. */
            speed: string | null;
        };
        ClientRecordHistory: {
            /** @description Every visit done: a completed visit with a window. */
            visits: number;
            services: number;
            replacements: number;
            /** @description India's date. Null when no first fit is on record, which is not the same as none. */
            first_fit_on: string | null;
            /** @description India's date of the latest visit done. */
            last_visit_on: string | null;
            /** @description In paise: every payment captured, less what has gone back. A credit adds nothing. */
            spend: number;
            /** @description When the piece now in wear falls due; null when the client is wearing none. */
            replacement_due: {
                /** Format: date */
                on: string;
                month: string;
                piece_code: string;
            } | null;
        };
        ClientPhotos: {
            visits: {
                /** Format: uuid */
                visit_id: string;
                /** Format: date */
                date: string;
                type: ("consultation" | "first_fit" | "service" | "replacement") | null;
                technician: {
                    name: string;
                    initials: string;
                } | null;
                /** @description Before then after, each in the design's angle order. */
                photos: components["schemas"]["ClientPhoto"][];
            }[];
        };
        ClientPhoto: {
            /**
             * Format: uuid
             * @description For GET /api/clients/{id}/photos/{photo_id}, which is audited.
             */
            id: string;
            /** @enum {string} */
            phase: "before" | "after";
            /** @enum {string} */
            angle: "front" | "top" | "left" | "right" | "hair";
            width: number | null;
            height: number | null;
            /** Format: date-time */
            taken_at: string;
        };
        ClientConsents: {
            consents: {
                /** @enum {string} */
                purpose: "photos_own_record" | "photos_referral_cards" | "photos_marketing" | "whatsapp_visits" | "whatsapp_launches";
                /**
                 * @description not_given until the client first switches it on; withdrawn once they switch it back off.
                 * @enum {string}
                 */
                state: "given" | "withdrawn" | "not_given";
                /** @description The notice the client saw when they last switched it. */
                notice_version: string | null;
                /** @description When they last switched it. */
                at: string | null;
            }[];
            /** @description Their latest deletion request. A processed one leaves no client to read. */
            deletion: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                state: "requested" | "rejected";
                /** Format: date-time */
                requested_at: string;
                decided_at: string | null;
            } | null;
        };
        NumberChangeDecision: {
            /** @enum {string} */
            decision: "confirm" | "reject";
            /** @description Required to reject; kept with the decision. */
            reason: string | null;
        };
        ErasureRefused: {
            error: {
                /** @enum {string} */
                code: "visit_booked" | "payment_held";
                request_id: string;
            };
            visits: {
                id: string;
                /** @enum {string|null} */
                type: "consultation" | "first_fit" | "service" | "replacement" | null;
                /** @enum {string} */
                status: "scheduled" | "dispatched" | "in_progress";
                /** Format: date-time */
                window_start: string | null;
            }[];
            payments: {
                id: string;
                reference: string | null;
                /** @description In paise. */
                amount: number;
            }[];
        };
        DeletionDecision: {
            /** @enum {string} */
            decision: "delete" | "reject";
            /** @description Required to reject; kept with the decision. */
            reason: string | null;
        };
        ReferralDecision: {
            /** @enum {string} */
            decision: "approve" | "reject";
            /** @description Required to reject, and kept with the decision either way. */
            reason: string | null;
        };
        GrievanceAnswer: {
            response: string;
        };
        PincodeLaunch: {
            confirm: boolean;
            /**
             * Format: date
             * @description India's date it starts; today if left out.
             */
            launch_on?: string;
        };
        DispatchBoard: {
            /** Format: date */
            from: string;
            /** @description 7 days, the board's columns. */
            dates: string[];
            technicians: {
                /** Format: uuid */
                technician_id: string;
                name: string;
                initials: string;
                zone: string | null;
                days: {
                    /** Format: date */
                    date: string;
                    blocks: components["schemas"]["DispatchBlock"][];
                }[];
            }[];
            unassigned: {
                /** Format: uuid */
                appointment_id: string;
                type: ("consultation" | "first_fit" | "service" | "replacement") | null;
                /** @description The window the client asked for, from the Request behind the visit; null where nothing recorded one. */
                asked_window: ("morning" | "afternoon" | "evening") | null;
                offered_window: ("morning" | "afternoon" | "evening") | null;
                date: string | null;
                sector: string | null;
            }[];
            /** @description Each column's utilisation, in per cent. Written to events daily as well. */
            utilisation: {
                /** Format: date */
                date: string;
                percent: number;
            }[];
            /** @description Leave ops recorded, clipped to this week. Not from FSM: its availability answers free time, not leave. */
            leave: {
                /** Format: uuid */
                technician_id: string;
                /** Format: date */
                from: string;
                /** Format: date */
                to: string;
                note: string | null;
            }[];
        };
        DispatchBlock: {
            /** Format: uuid */
            appointment_id: string;
            type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            /** Format: date-time */
            starts_at: string;
            /** @enum {string} */
            window: "morning" | "afternoon" | "evening";
            /** @description Consultation 1, service 1, replacement 1.5, first fit 2. */
            slots: number;
            /** @enum {string} */
            status: "scheduled" | "dispatched" | "in_progress" | "completed" | "cancelled" | "terminated" | "other";
            /** @description First name and last initial. */
            client: string | null;
            sector: string | null;
        };
        DispatchMoved: {
            /** Format: uuid */
            move_id: string;
            /** @description The client was told his new window. */
            messaged: boolean;
        };
        DispatchAssignRequest: {
            /** Format: uuid */
            appointment_id: string;
            /** Format: uuid */
            technician_id: string;
            /** Format: date */
            date?: string;
            /** @enum {string} */
            window?: "morning" | "afternoon" | "evening";
            /** @enum {string} */
            reason: "technician_unavailable" | "client_asked" | "zone_rebalance" | "skill_needed" | "running_over";
        };
        DispatchMoveRequest: {
            /** Format: uuid */
            appointment_id: string;
            /**
             * Format: uuid
             * @description Left out keeps the technician it has.
             */
            technician_id?: string;
            /** Format: date */
            date?: string;
            /** @enum {string} */
            window?: "morning" | "afternoon" | "evening";
            /** @enum {string} */
            reason: "technician_unavailable" | "client_asked" | "zone_rebalance" | "skill_needed" | "running_over";
        };
        NoShowCases: {
            cases: components["schemas"]["NoShowCase"][];
        };
        /** @description The three facts ops rule on, and nothing else. */
        NoShowCase: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            appointment_id: string;
            visit_date: string | null;
            technician: string | null;
            /**
             * Format: date-time
             * @description Fact one: when the technician arrived, by his phone, held within bounds. The wait ran from here.
             */
            checked_in_at: string;
            /** @description What the phone itself said, before the bounds; null when it said nothing. */
            phone_checked_in_at: string | null;
            /**
             * Format: date-time
             * @description When the check-in reached us: long after the phone's time means no signal, or a clock set back.
             */
            received_at: string;
            /** @description The visit's booked window. */
            window_start: string | null;
            window_end: string | null;
            /** @description Minutes from the booked start to the check-in; negative when he was early. */
            minutes_late: number | null;
            /** @description Fact two: how far from the address he was; null where the address had no coordinates and nothing was measured. */
            distance_m: number | null;
            /** @description Fact three: when WhatsApp reported the visit message delivered; null if never. */
            message_delivered_at: string | null;
            /** Format: date-time */
            wait_ends_at: string;
            closed_at: string | null;
            /** @enum {string} */
            decision: "undecided" | "charged" | "waived";
            decided_at: string | null;
        };
        NoShowDecisionRequest: {
            /** @enum {string} */
            decision: "charged" | "waived";
        };
        ClientPieces: {
            pieces: components["schemas"]["Piece"][];
        };
        Piece: {
            piece_code: string;
            base: string | null;
            supplier_lot: string | null;
            fitted_at: string | null;
            replacement_due_at: string | null;
            failed_at: string | null;
            failure_reason: string | null;
        };
        Technicians: {
            technicians: {
                /** Format: uuid */
                id: string;
                name: string;
                initials: string;
                zone: string | null;
                devices: {
                    device_id: string;
                    label: string | null;
                    /** Format: date-time */
                    last_seen_at: string;
                    revoked_at: string | null;
                }[];
                /** @description Leave that has not ended yet, soonest first (ADR 0062). */
                leave: components["schemas"]["TechnicianLeave"][];
            }[];
        };
        TechnicianLeave: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            from: string;
            /**
             * Format: date
             * @description Inclusive: a single day's leave has the same date twice.
             */
            to: string;
            note: string | null;
        };
        TechnicianLeaveRequest: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** @description Why, in ops' words. Never a medical detail. */
            note?: string;
        };
        /** @description Derived at read time from the queues themselves; there is no tasks table. */
        Tasks: {
            /** @description How many are past their day in India, across every group. */
            overdue: number;
            groups: {
                /** @enum {string} */
                group: "consultation_request" | "replacement_order" | "referral_review" | "no_show_decision" | "number_change" | "erasure_request";
                count: number;
                /** @description The longest wait first. */
                tasks: components["schemas"]["Task"][];
            }[];
        };
        Task: {
            /**
             * Format: uuid
             * @description The queued row's own id, so the task can be reached where it is decided.
             */
            id: string;
            /** @description Null for a no-show, whose case names the technician and never the client. */
            person: {
                /** Format: uuid */
                id: string;
                name: string;
            } | null;
            /** @description The one fact the group turns on: a piece's label, a fraud rule, a technician. */
            detail: string | null;
            /**
             * Format: date-time
             * @description When it started waiting.
             */
            since: string;
            /**
             * Format: date-time
             * @description since plus the group's allowance, which ops set; 48 hours until they do.
             */
            due: string;
        };
        /** @description Derived at read time from the payments themselves; no total is kept. */
        OpsDayMoney: {
            /**
             * Format: date
             * @description India's calendar date the figures cover.
             */
            date: string;
            /** @description In paise. Captured on the day: the board's "Collected today". */
            collected: number;
            /** @description In paise. Asked for on the day and not back with the client yet: "Refunds processing". */
            refunds_processing: number;
            /** @description In paise. Processed by Razorpay on the day, which the board draws no figure of its own for. */
            refunded: number;
            /** @description In paise. Kept from the client on the day: "Charges and no-shows", less the no-shows, which carry no amount. */
            charged: number;
            /** @description How many no-shows ops ruled charged on the day. Counted and not added, because nothing records what one was charged (docs/open-points.md, item 57). */
            no_shows_charged: number;
            /** @description The charge under dispute, with the note ops write on it. Nothing records a dispute and no client can raise one, so this is always null (docs/open-points.md, item 57). */
            dispute: null;
            /** @description No-shows and late cancellations, the earliest first. */
            charges: components["schemas"]["OpsCharge"][];
        };
        OpsCharge: {
            /**
             * Format: uuid
             * @description The change's or the case's own id.
             */
            id: string;
            /** @enum {string} */
            kind: "late_cancellation" | "no_show";
            /** @description Null for a visit FSM never matched to one of our people. */
            person: {
                /** Format: uuid */
                id: string;
                name: string;
            } | null;
            /** @description Null on a no-show: ops record the ruling and nothing records an amount, because the charge itself is applied at P2-M5. */
            amount: number | null;
            /**
             * Format: date-time
             * @description When the client cancelled, or when ops ruled on the no-show.
             */
            at: string;
            /** @description When the visit was to start. */
            visit_started_at: string | null;
            /** @description How the client ended the visit; null on a no-show, where they ended nothing. */
            change: ("cancelled" | "moved") | null;
            /** @description Who attended and found nobody in; null on a late cancellation. */
            technician: string | null;
        };
        /** @description Counted at read time from the appointments themselves. */
        TechniciansWork: {
            /** Format: date */
            from: string;
            /**
             * Format: date
             * @description Exclusive: the day after the last one counted.
             */
            to: string;
            /** @description Every active technician, by name, including those who finished nothing. */
            technicians: components["schemas"]["TechnicianWork"][];
        };
        TechnicianWork: {
            /** Format: uuid */
            technician_id: string;
            /** @description Visits completed in the period. */
            jobs: number;
            /** @description Of those, the ones the phone timed from Start to the outcome: what the averages are the mean of. */
            timed_jobs: number;
            /** @description How long those took; null when the phone timed none of them. */
            average_minutes: number | null;
            /** @description What the same jobs were planned to take, so the two can be read against each other. */
            average_planned_minutes: number | null;
            /** @description The board's "First fit" or "Service". Nothing records what a technician is trained for and the FSM user carries no such field, so this is always null (docs/open-points.md, item 59). */
            skill: null;
        };
        OpsSetting: {
            name: string;
            title: string;
            note: string;
            unit: string;
            min: number;
            max: number;
            /** @description null for one number, a list where the keys are fixed, "open" where ops name them. */
            keys: string[] | "open" | null;
            value: number | {
                [key: string]: number;
            };
            /** @description The committed figure, in force until somebody sets one. */
            default: number | {
                [key: string]: number;
            };
            /** @description The module the default lives in. */
            source: string;
            set_by: string | null;
            set_at: string | null;
        };
        SettingChange: {
            value: number | {
                [key: string]: number;
            } | null;
        };
        Price: {
            item: string;
            tier: string;
            /** @description In paise, before GST. */
            amount_ex_gst: number;
            gst_percent: number;
            /**
             * Format: date
             * @description India's date it applies from.
             */
            valid_from: string;
            in_force: boolean;
        };
        PriceChange: {
            item: string;
            tier: string;
            amount_ex_gst: number;
            gst_percent: number;
            /** Format: date */
            valid_from: string;
        };
        ServedPincode: {
            pincode: string;
            area: string;
            city: string;
            served: boolean;
            launch_on: string | null;
        };
        ServiceAreaChange: {
            changes: {
                pincode: string;
                served: boolean;
                launch_on: string | null;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
