/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment, version and database reachability */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                /** @description The database is unreachable or belongs to another environment */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a login code on WhatsApp. The answer is the same whether or not the number has a booking */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description A code is on its way, if this number has a booking */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginChallenge"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description rate_limited: too many codes for this number today, or from this address this hour */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy: today's ceiling on codes is reached */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a fresh code on WhatsApp, 30 seconds after the last one */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginChallengeRequest"];
                };
            };
            responses: {
                /** @description A code is on its way, if this number has a booking */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginChallenge"];
                    };
                };
                /** @description code_expired: start again */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description too_early, or rate_limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a fresh code by SMS instead, 30 seconds after the first */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginChallengeRequest"];
                };
            };
            responses: {
                /** @description A code is on its way, if this number has a booking */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginChallenge"];
                    };
                };
                /** @description not_found: SMS is not available */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description code_expired: start again */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description too_early, or rate_limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check a code. The right one opens a session (the mm_app cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginVerifyRequest"];
                };
            };
            responses: {
                /** @description Right, with a session; or wrong, with the attempts left */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginVerify"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description code_expired: expired, used, or void after five wrong codes */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Home card: who the client is and what is booked */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The Home card */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The profile: name, number, address, consents, and any number change or deletion under way */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Replace the address visits go to, with its access notes */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Address"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/consents/{purpose}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Switch one consent on or off. Each switch is kept, with its date */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    purpose: "photos_own_record" | "photos_referral_cards" | "photos_marketing" | "whatsapp_visits" | "whatsapp_launches";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConsentSwitch"];
                };
            };
            responses: {
                /** @description Switched */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            purpose: "photos_own_record" | "photos_referral_cards" | "photos_marketing" | "whatsapp_visits" | "whatsapp_launches";
                            granted: boolean;
                            /** Format: date-time */
                            since: string;
                        };
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/number-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a number change: a code goes to both numbers. Starting again withdraws the last one */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NumberChangeStart"];
                };
            };
            responses: {
                /** @description Codes on their way to both numbers */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            request_id: string;
                            expires_in_s: number;
                        };
                    };
                };
                /** @description invalid_request: not an Indian mobile number, or the number already in use here */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description rate_limited: three changes a day */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/number-change/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** One number's code. With both numbers proven, the change waits for ops to confirm */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NumberChangeVerify"];
                };
            };
            responses: {
                /** @description Checked. attempts_left is null when the code was right */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            request_id: string;
                            /** @enum {string} */
                            state: "verifying" | "awaiting_ops";
                            /** @description Masked, as the design shows it: +91 98xxx x4417. */
                            new_mobile: string;
                            old_verified: boolean;
                            new_verified: boolean;
                            attempts_left: number | null;
                        };
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description code_expired: the code or the change is closed; start again */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deletion-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask for the account to be deleted. Ops process it; asking twice makes one request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Requested */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            state: "requested";
                            /** Format: date-time */
                            requested_at: string;
                        };
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The client's visits, upcoming and past */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Upcoming soonest first; past newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Visits"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of the client's visits, with its photographs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The visit */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VisitDetail"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such visit of this client's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The client's photographs, by visit, newest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Visits that have photographs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoTimeline"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One angle from two of the client's visits, to compare */
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                    angle: "front" | "top" | "left" | "right" | "hair";
                    phase?: "before" | "after";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Both photographs, or null where a visit has none of that angle */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoCompare"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: a visit that is not this client's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/file/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A photograph, through a link that lasts 15 minutes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                        "image/png": string;
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: the link is wrong, expired, or not this client's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the client paid, newest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The client's payments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            payments: components["schemas"]["Payment"][];
                        };
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of the client's payments, with its refunds */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The payment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentDetail"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such payment of this client's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A visit's invoice, as a PDF from Books */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The visit's ID. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The PDF */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such visit of this client's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_ready: Books has not raised the invoice yet; the app shows "Document unavailable" */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "not_found" | "invalid_request" | "turnstile_failed" | "rate_limited" | "idempotency_in_progress" | "idempotency_key_reused" | "environment_mismatch" | "unavailable" | "internal_error" | "busy" | "photo_invalid_file" | "upload_already_received" | "upload_missing" | "session_required" | "job_not_claimable" | "look_limit_reached" | "unauthorized" | "forbidden_origin" | "access_required" | "code_expired" | "too_early" | "number_in_use" | "not_ready";
                request_id: string;
                /** @description invalid_request only: the fields that failed validation, never their values. */
                fields?: string[];
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @enum {string} */
            environment: "local" | "staging" | "production";
            /** @description Cloudflare Worker version ID serving this request. */
            version_id: string;
            /** @description Tag given at upload: the git commit SHA in remote environments. */
            version_tag: string | null;
            /**
             * @description ok: reachable and marked as this environment's database. unmarked: no identity row. mismatch: marked as another environment's database.
             * @enum {string}
             */
            d1: "ok" | "unmarked" | "mismatch" | "unreachable";
        };
        LoginChallenge: {
            /** Format: uuid */
            challenge_id: string;
            /**
             * @description How the current code was sent.
             * @enum {string}
             */
            channel: "whatsapp" | "sms";
            expires_in_s: number;
            /** @description Seconds until the code may be sent again on WhatsApp. */
            resend_in_s: number;
            /** @description Seconds until SMS may be asked for instead; null while SMS is unavailable. */
            sms_in_s: number | null;
        };
        LoginRequest: {
            /** @example 98100 00000 */
            mobile: string;
        };
        LoginChallengeRequest: {
            /** Format: uuid */
            challenge_id: string;
        };
        LoginVerify: {
            /** @enum {boolean} */
            verified: true;
            first_name: string;
        } | {
            /** @enum {boolean} */
            verified: false;
            /** @description 0 means the code is now void. */
            attempts_left: number;
        };
        LoginVerifyRequest: {
            /** Format: uuid */
            challenge_id: string;
            code: string;
        };
        Me: {
            /** @enum {string} */
            state: "fitted" | "lead" | "nothing_booked";
            name: string;
            first_name: string;
            /** @description For the profile's button: the first letters of the first and last names. */
            initials: string;
            /** @description A Phase 1 booking's proposed consultation, to be confirmed on WhatsApp. Null once the mirror has the visit. */
            consultation: {
                /** Format: date */
                date: string;
                /** @enum {string} */
                window_label: "before noon" | "after four";
                /** @description Where it is: the saved address (locality, city and pincode), else the booking's city. */
                place: string;
            } | null;
            /** @description The next visit that has not happened, from FSM: a consultation for a lead. */
            next_visit: components["schemas"]["VisitSummary"] | null;
            /** @description The credit tile: balance and earliest expiry. Arrives with the credit ledger (P2-M3). */
            credits: null;
            /** @description The one contextual prompt, e.g. a replacement due. Arrives with the pieces (P2-M4). */
            prompt: null;
        };
        VisitSummary: {
            /** Format: uuid */
            id: string;
            /**
             * Format: date
             * @description India's calendar date.
             */
            date: string;
            /** @enum {string} */
            window_label: "morning" | "afternoon" | "evening";
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            length_minutes: number;
            type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            /** @enum {string} */
            status: "scheduled" | "dispatched" | "in_progress" | "completed" | "cancelled" | "terminated" | "other";
            technician: components["schemas"]["Technician"] | null;
            /** @description The saved address's area, city and pincode, else FSM's city and pincode. */
            place: string;
        };
        /** @description Display name and initials only. */
        Technician: {
            name: string;
            initials: string;
        };
        Profile: {
            name: string;
            /** @description Masked: +91 98xxx x4417. */
            mobile: string;
            address: components["schemas"]["Address"] | null;
            /** @description The five purposes, in order. Off until the client first switches one on. */
            consents: {
                /** @enum {string} */
                purpose: "photos_own_record" | "photos_referral_cards" | "photos_marketing" | "whatsapp_visits" | "whatsapp_launches";
                granted: boolean;
                /** Format: date-time */
                since: string | null;
            }[];
            number_change: components["schemas"]["NumberChange"] | null;
            deletion: {
                /** @enum {string} */
                state: "requested";
                /** Format: date-time */
                requested_at: string;
            } | null;
        };
        Address: {
            line1: string;
            line2: string | null;
            locality: string;
            city: string;
            pincode: string;
            /** @description For the technician, from the day before the visit: gate code, parking. */
            access_notes: string | null;
        };
        NumberChange: {
            /** Format: uuid */
            request_id: string;
            /** @enum {string} */
            state: "verifying" | "awaiting_ops";
            /** @description Masked, as the design shows it: +91 98xxx x4417. */
            new_mobile: string;
            old_verified: boolean;
            new_verified: boolean;
        };
        ConsentSwitch: {
            granted: boolean;
        };
        NumberChangeStart: {
            new_mobile: string;
        };
        NumberChangeVerify: {
            /** Format: uuid */
            request_id: string;
            /** @enum {string} */
            number: "old" | "new";
            code: string;
        };
        Visits: {
            upcoming: components["schemas"]["VisitSummary"][];
            past: components["schemas"]["VisitSummary"][];
        };
        VisitDetail: components["schemas"]["VisitSummary"] & {
            /** @description From start to finish, once done. */
            duration_minutes: number | null;
            outcome: ("done" | "partial") | null;
            photos: components["schemas"]["PhotoSet"];
            /** @description The visit's invoice, for GET /api/documents/{id}, once Books has raised it. */
            document_id: string | null;
        };
        /** @description Each angle in the order front, top, left, right, hair; missing angles left out. */
        PhotoSet: {
            before: components["schemas"]["PhotoLink"][];
            after: components["schemas"]["PhotoLink"][];
        };
        PhotoLink: {
            /** @enum {string} */
            angle: "front" | "top" | "left" | "right" | "hair";
            /** @description Lasts 15 minutes; only the signed-in client can open it. */
            url: string;
            width: number | null;
            height: number | null;
        };
        PhotoTimeline: {
            visits: {
                /** Format: uuid */
                visit_id: string;
                /** Format: date */
                date: string;
                type: ("consultation" | "first_fit" | "service" | "replacement") | null;
                photos: components["schemas"]["PhotoSet"];
            }[];
        };
        PhotoCompare: {
            /** @enum {string} */
            angle: "front" | "top" | "left" | "right" | "hair";
            /** @enum {string} */
            phase: "before" | "after";
            from: {
                /** Format: uuid */
                visit_id: string;
                /** Format: date */
                date: string;
                photo: components["schemas"]["PhotoLink"] | null;
            };
            to: {
                /** Format: uuid */
                visit_id: string;
                /** Format: date */
                date: string;
                photo: components["schemas"]["PhotoLink"] | null;
            };
        };
        Payment: {
            /** Format: uuid */
            id: string;
            /** @description Ours, e.g. MM-2026-0841, once captured. */
            reference: string | null;
            /**
             * Format: date
             * @description India's calendar date the payment was made.
             */
            date: string;
            /** @description In paise, GST included. */
            amount: number;
            /** @description In paise: refunds Razorpay has processed. */
            refunded_amount: number;
            /** @enum {string} */
            status: "authorized" | "captured" | "failed" | "refunded" | "partially_refunded";
            /** @description upi, card, netbanking and so on. */
            method: string | null;
            /** @description The visit it paid for, when known. */
            visit: {
                /** Format: uuid */
                id: string;
                /** Format: date */
                date: string;
                type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            } | null;
        };
        PaymentDetail: components["schemas"]["Payment"] & {
            refunds: {
                amount: number;
                /** @enum {string} */
                status: "created" | "processed" | "failed";
                /** @description normal (5 to 7 working days) or instant. */
                speed: string | null;
                /** Format: date */
                date: string;
            }[];
            /** @description The visit's invoice, for GET /api/documents/{id}, once Books has raised it. */
            document_id: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
