/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment, version and database reachability */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                /** @description The database is unreachable or belongs to another environment */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a login code on WhatsApp. The answer is the same whether or not the number has a booking */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description A code is on its way, if this number has a booking */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginChallenge"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description rate_limited: too many codes for this number today, or from this address this hour */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy: today's ceiling on codes is reached */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a fresh code on WhatsApp, 30 seconds after the last one */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginChallengeRequest"];
                };
            };
            responses: {
                /** @description A code is on its way, if this number has a booking */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginChallenge"];
                    };
                };
                /** @description code_expired: start again */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description too_early, or rate_limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a fresh code by SMS instead, 30 seconds after the first */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginChallengeRequest"];
                };
            };
            responses: {
                /** @description A code is on its way, if this number has a booking */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginChallenge"];
                    };
                };
                /** @description not_found: SMS is not available */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description code_expired: start again */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description too_early, or rate_limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check a code. The right one opens a session (the mm_app cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginVerifyRequest"];
                };
            };
            responses: {
                /** @description Right, with a session; or wrong, with the attempts left */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginVerify"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description code_expired: expired, used, or void after five wrong codes */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Home card: who the client is and what is booked */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The Home card */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The profile: name, number, address, consents, and any number change or deletion under way */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Replace the address visits go to, with its access notes */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Address"];
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Address"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/consents/{purpose}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Switch one consent on or off. Each switch is kept, with its date */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    purpose: "photos_own_record" | "photos_referral_cards" | "photos_marketing" | "whatsapp_visits" | "whatsapp_launches";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConsentSwitch"];
                };
            };
            responses: {
                /** @description Switched */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            purpose: "photos_own_record" | "photos_referral_cards" | "photos_marketing" | "whatsapp_visits" | "whatsapp_launches";
                            granted: boolean;
                            /** Format: date-time */
                            since: string;
                        };
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/number-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a number change: a code goes to both numbers. Starting again withdraws the last one */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NumberChangeStart"];
                };
            };
            responses: {
                /** @description Codes on their way to both numbers */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            request_id: string;
                            expires_in_s: number;
                        };
                    };
                };
                /** @description invalid_request: not an Indian mobile number, or the number already in use here */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description rate_limited: three changes a day */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/number-change/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** One number's code. With both numbers proven, the change waits for ops to confirm */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NumberChangeVerify"];
                };
            };
            responses: {
                /** @description Checked. attempts_left is null when the code was right */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            request_id: string;
                            /** @enum {string} */
                            state: "verifying" | "awaiting_ops";
                            /** @description Masked, as the design shows it: +91 98xxx x4417. */
                            new_mobile: string;
                            old_verified: boolean;
                            new_verified: boolean;
                            attempts_left: number | null;
                        };
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description code_expired: the code or the change is closed; start again */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deletion-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask for the account to be deleted. Ops process it; asking twice makes one request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Requested */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            state: "requested";
                            /** Format: date-time */
                            requested_at: string;
                        };
                    };
                };
                /** @description session_required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "not_found" | "invalid_request" | "turnstile_failed" | "rate_limited" | "idempotency_in_progress" | "idempotency_key_reused" | "environment_mismatch" | "unavailable" | "internal_error" | "busy" | "photo_invalid_file" | "upload_already_received" | "upload_missing" | "session_required" | "job_not_claimable" | "look_limit_reached" | "unauthorized" | "forbidden_origin" | "access_required" | "code_expired" | "too_early" | "number_in_use" | "not_ready";
                request_id: string;
                /** @description invalid_request only: the fields that failed validation, never their values. */
                fields?: string[];
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @enum {string} */
            environment: "local" | "staging" | "production";
            /** @description Cloudflare Worker version ID serving this request. */
            version_id: string;
            /** @description Tag given at upload: the git commit SHA in remote environments. */
            version_tag: string | null;
            /**
             * @description ok: reachable and marked as this environment's database. unmarked: no identity row. mismatch: marked as another environment's database.
             * @enum {string}
             */
            d1: "ok" | "unmarked" | "mismatch" | "unreachable";
        };
        LoginChallenge: {
            /** Format: uuid */
            challenge_id: string;
            /**
             * @description How the current code was sent.
             * @enum {string}
             */
            channel: "whatsapp" | "sms";
            expires_in_s: number;
            /** @description Seconds until the code may be sent again on WhatsApp. */
            resend_in_s: number;
            /** @description Seconds until SMS may be asked for instead; null while SMS is unavailable. */
            sms_in_s: number | null;
        };
        LoginRequest: {
            /** @example 98100 00000 */
            mobile: string;
        };
        LoginChallengeRequest: {
            /** Format: uuid */
            challenge_id: string;
        };
        LoginVerify: {
            /** @enum {boolean} */
            verified: true;
            first_name: string;
        } | {
            /** @enum {boolean} */
            verified: false;
            /** @description 0 means the code is now void. */
            attempts_left: number;
        };
        LoginVerifyRequest: {
            /** Format: uuid */
            challenge_id: string;
            code: string;
        };
        Me: {
            /** @enum {string} */
            state: "lead" | "nothing_booked";
            name: string;
            first_name: string;
            /** @description For the profile's button: the first letters of the first and last names. */
            initials: string;
            /** @description The booked consultation: its proposed date and window, to be confirmed on WhatsApp. */
            consultation: {
                /** Format: date */
                date: string;
                /** @enum {string} */
                window_label: "before noon" | "after four";
                /** @description Where it is: the saved address (locality, city and pincode), else the booking's city. */
                place: string;
            } | null;
        };
        Profile: {
            name: string;
            /** @description Masked: +91 98xxx x4417. */
            mobile: string;
            address: components["schemas"]["Address"] | null;
            /** @description The five purposes, in order. Off until the client first switches one on. */
            consents: {
                /** @enum {string} */
                purpose: "photos_own_record" | "photos_referral_cards" | "photos_marketing" | "whatsapp_visits" | "whatsapp_launches";
                granted: boolean;
                /** Format: date-time */
                since: string | null;
            }[];
            number_change: components["schemas"]["NumberChange"] | null;
            deletion: {
                /** @enum {string} */
                state: "requested";
                /** Format: date-time */
                requested_at: string;
            } | null;
        };
        Address: {
            line1: string;
            line2: string | null;
            locality: string;
            city: string;
            pincode: string;
            /** @description For the technician, from the day before the visit: gate code, parking. */
            access_notes: string | null;
        };
        NumberChange: {
            /** Format: uuid */
            request_id: string;
            /** @enum {string} */
            state: "verifying" | "awaiting_ops";
            /** @description Masked, as the design shows it: +91 98xxx x4417. */
            new_mobile: string;
            old_verified: boolean;
            new_verified: boolean;
        };
        ConsentSwitch: {
            granted: boolean;
        };
        NumberChangeStart: {
            new_mobile: string;
        };
        NumberChangeVerify: {
            /** Format: uuid */
            request_id: string;
            /** @enum {string} */
            number: "old" | "new";
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
