-- Migration number: 0025
-- withdrawn: deploy-staging run 35816407888 refused it, and it has been applied nowhere.
--
-- It rebuilt the leads table to make loss_extent and first_choice_window
-- optional, so that a Phase 2 booking could leave a lead behind it
-- (docs/decisions/0051-booking-from-the-site.md).
--
-- Two things were wrong with that. first_choice_window was already optional, so
-- only loss_extent needed anything. And a table that another table points at
-- cannot be rebuilt inside one transaction: a try-on job points at a lead
-- (migration 0003), and dropping the parent counts as a foreign key violation
-- that re-creating it does not undo, whatever PRAGMA defer_foreign_keys says.
-- SQLite's own recipe turns foreign keys off around the rebuild, and D1 runs a
-- migration in one transaction, where that pragma does nothing.
--
-- So nothing is rebuilt. The site's own booking form asks where the hair loss
-- is, as it always has, so its lead has the column it needs. An invited friend
-- is not asked, and the referral landing leaves no lead, as it did before
-- (docs/open-points.md, item 50).

-- A migration must contain a statement, and this one has nothing left to do.
SELECT 1;
