/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment, version and database reachability */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                /** @description The database is unreachable or belongs to another environment */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client-errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report an error in the app's own page */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientErrorReport"];
                };
            };
            responses: {
                /** @description Logged */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description rate_limited: this address has sent its reports for the hour, or every address has */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a login code on WhatsApp. The answer is the same whether or not FSM lists the number */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianLoginRequest"];
                };
            };
            responses: {
                /** @description A code is on its way, if FSM lists this number */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianChallenge"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description rate_limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy: today's ceiling on codes is reached */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check a code. The right one opens a session on this phone (the mm_tech cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianVerifyRequest"];
                };
            };
            responses: {
                /** @description Right, with a session; or wrong, with the attempts left */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianVerify"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description code_expired: expired, used, or void after five wrong codes */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session on this phone */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description session_required; device_revoked: there was no session here to end */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in, and the phone this session is bound to */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The signed-in technician */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianMe"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs; technician_inactive: ops switched him off, so drop the cards and set aside the work not yet sent */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The technician's jobs on a date. Today and tomorrow in full; later dates only time, type and sector */
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The day's jobs, in time order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianJobs"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of the technician's jobs, with the day-before unlock enforced */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianJobDetail"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job of this technician's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/last-visit-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The client's last visit, after: one photograph, under the card's own unlock, never cached */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                        "image/png": string;
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job of this technician's, not unlocked yet, or no earlier visit's photograph */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** I have arrived: the time and the phone's position, inside the geofence */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckInRequest"];
                };
            };
            responses: {
                /** @description Pass or fail, with the distance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckIn"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first; not_today: the job is on another day */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the job. The duration runs from here to the outcome */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first; not_today: the job is on another day */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/photos/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A link to PUT one photograph to, for one phase and angle */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianPhotoUrlRequest"];
                };
            };
            responses: {
                /** @description The link, good for fifteen minutes */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianPhotoUrl"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job, or never this technician's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: the job was given to another technician or cancelled while its photographs waited; moved names whom */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/photos/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** The photograph itself: a JPEG or PNG, at most 2 MB */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Received */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianPhotoTaken"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: the link is wrong or expired */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_invalid_file: not a JPEG or PNG, or over 2 MB */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy: R2 holds past the runaway ceiling; the phone keeps the photograph and sends it later */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/photos/{token}/small": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** The photograph's small copy, for the client app's rows: a JPEG of at most 64 KB and 800 px a side */
        put: {
            parameters: {
                query: {
                    /** @description The take the photograph's upload answered. */
                    take: string;
                };
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Received, or held already */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: the link is wrong or expired */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description upload_missing: that take is not the angle's photograph: not arrived yet, or taken again since */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_invalid_file: not a JPEG, or over 64 KB or 800 px a side */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy: R2 holds past the runaway ceiling */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The phase's five photographs are in; attach them to FSM */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianPhotosRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The service checklist, per visit type */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChecklistRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/consumables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consumables used, with quantities */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConsumablesRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/piece": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The piece: a replacement's, a first fit's and a one visit's step only */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PieceRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first; piece_code: a label already on record, as another client's piece or this client's from an earlier visit, or a piece that came off that is another client's. error.fields names piece_code or old_piece, to correct and send again */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The client's hair profile, the fit spec and their history, as a new version */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianProfileRequest"];
                };
            };
            responses: {
                /** @description Recorded; or, for a job with no client of ours, taken and nothing written. One taken from an older version than the latest still lands, and ops are told. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianProfileRecorded"];
                    };
                };
                /** @description invalid_request: see error.fields; visit, for a visit that takes no profile */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Done, or partial with a reason */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OutcomeRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/no-show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close the job as a no-show, once the wait has run */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Closed, with the case ops will rule on */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoShowClose"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first; already_started: the job was started, so the client was home */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description too_early_to_close: the wait has not run out */
                425: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/pieces/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The piece a label names */
        get: {
            parameters: {
                query: {
                    code: string;
                    job?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The piece */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PieceLookup"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no piece with that label */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/discount-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enter a discount code on a one visit, before its payment link is made */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianDiscountCode"];
                };
            };
            responses: {
                /** @description It comes off the product's price at the payment link */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianDiscountCodeApplied"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job of this technician's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description already_discounted: the visit carries a code; price_settled: its payment link is made, or it is not a one visit, whose client paid ahead */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description code_not_applicable: the code does not apply to this visit */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description rate_limited: too many codes tried today, or from this address this hour */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "not_found" | "invalid_request" | "turnstile_failed" | "rate_limited" | "idempotency_in_progress" | "idempotency_key_reused" | "environment_mismatch" | "unavailable" | "internal_error" | "busy" | "photo_invalid_file" | "upload_already_received" | "upload_missing" | "session_required" | "job_not_claimable" | "look_limit_reached" | "claim_required" | "whatsapp_unavailable" | "number_not_proved" | "unauthorized" | "visit_booked" | "payment_held" | "forbidden_origin" | "access_required" | "code_expired" | "too_early" | "number_in_use" | "not_ready" | "ops_assisted" | "taken" | "not_bookable" | "hold_expired" | "address_required" | "already_booked" | "not_changeable" | "terms_changed" | "consent_required" | "device_revoked" | "superseded" | "out_of_order" | "not_today" | "already_started" | "piece_code" | "technician_inactive" | "managed_in_fsm" | "clash" | "on_leave" | "does_not_fit" | "fsm_refused" | "fsm_partly" | "in_progress" | "too_early_to_close" | "already_closed" | "no_service_area" | "service_exists" | "last_of_kind" | "service_retired" | "no_product" | "unknown_invite" | "own_invite" | "already_invited" | "already_disputed" | "not_disputable" | "dispute_window_closed" | "code_not_applicable" | "already_discounted" | "price_settled" | "code_exists" | "slot_times_too_soon" | "not_permitted" | "last_admin";
                request_id: string;
                /** @description invalid_request: the fields that failed validation, never their values; superseded: what changed under the caller. */
                fields?: string[];
                /** @description superseded, to a technician's phone, for a job given to another technician: whom, and when (docs/open-points.md, item 92). */
                moved?: {
                    /** @description Their first name, and nothing else of theirs */
                    technician: string;
                    /** @description When ops moved the job to them; null when it was moved in FSM itself */
                    at: string | null;
                };
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @enum {string} */
            environment: "local" | "staging" | "production";
            /** @description Cloudflare Worker version ID serving this request. */
            version_id: string;
            /** @description Tag given at upload: the git commit SHA in remote environments. */
            version_tag: string | null;
            /**
             * @description ok: reachable and marked as this environment's database. unmarked: no identity row. mismatch: marked as another environment's database.
             * @enum {string}
             */
            d1: "ok" | "unmarked" | "mismatch" | "unreachable";
            /** @description When the five-minute cron last finished a run; null before its first, or when the database is not this environment's. Information only: status does not depend on it. */
            cron_completed_at: string | null;
        };
        ClientErrorReport: {
            /** @enum {string} */
            kind: "error" | "unhandled_rejection" | "render" | "outbox_gave_up";
            message: string;
            /** @description The page's path, with no query or fragment. */
            path: string;
            stack?: string;
            /** @description The script the error was thrown in. */
            source?: string;
            line?: number;
            column?: number;
            /** @description outbox_gave_up: the write's kind, as `checklist`. */
            step?: string;
            /** @description outbox_gave_up: the code the API refused it with. */
            code?: string;
            /** @description outbox_gave_up: the refusal's HTTP status. */
            status?: number;
            /** @description outbox_gave_up: the refusal's request ID, which its own log lines carry. */
            request_id?: string;
        };
        TechnicianChallenge: {
            /** Format: uuid */
            challenge_id: string;
            expires_in_s: number;
        };
        TechnicianLoginRequest: {
            mobile: string;
            /** @description The app's own ID for this phone, kept in its storage. */
            device_id: string;
        };
        TechnicianVerify: {
            /** @enum {boolean} */
            verified: true;
            first_name: string;
            device_id: string;
        } | {
            /** @enum {boolean} */
            verified: false;
            attempts_left: number;
        };
        TechnicianVerifyRequest: {
            /** Format: uuid */
            challenge_id: string;
            code: string;
            /** @description The app's own ID for this phone, kept in its storage. */
            device_id: string;
        };
        TechnicianMe: {
            /**
             * Format: uuid
             * @description Whose work the phone holds: it keeps work it set aside only for him.
             */
            id: string;
            name: string;
            first_name: string;
            /** @description For the chip at the head of Today: the first and last initials. */
            initials: string;
            device: {
                /** @description The phone's own ID, as it sent it at sign-in. */
                device_id: string;
                /** @description Ours, from the User-Agent at sign-in. */
                label: string | null;
                /** Format: date-time */
                enrolled_at: string;
            };
        };
        /** @description Jobs further out carry only time, type and sector. */
        TechnicianJobs: {
            /** Format: date */
            date: string;
            jobs: components["schemas"]["TechnicianJob"][];
        };
        TechnicianJob: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            day: "today" | "tomorrow" | "later";
            /** Format: date */
            date: string;
            /** Format: date-time */
            starts_at: string;
            ends_at: string | null;
            /** @enum {string} */
            window_label: "morning" | "afternoon" | "evening";
            type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            /** @description A consultation and fit in one visit: the first fit's steps, with the client's choice of product, or none, at the piece step. */
            one_visit: boolean;
            /** @description On a first fit, the hair system the client was sold, by its name in the console. Null on any other visit, on a one visit until the client chooses, and on a first fit that names none. */
            product: string | null;
            /** @description The area, never the street: the one the visit's pincode is in, from the service area; else the address's locality, or the city. */
            sector: string | null;
            /** @enum {string} */
            status: "scheduled" | "dispatched" | "in_progress" | "completed" | "cancelled" | "terminated" | "other";
            /**
             * @description Free for a visit the price book charges nothing for; at_visit for a one visit, paid for once the client is fitted. No response to a technician carries an amount.
             * @enum {string}
             */
            badge: "prepaid" | "credit" | "free" | "at_visit";
            /** @description How much of the day the visit takes: 1, 1.5 or 2 slots. Null for an unknown type. */
            slots: number | null;
            unlocked: boolean;
            /** Format: date-time */
            unlocks_at: string;
        };
        TechnicianJobDetail: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            day: "today" | "tomorrow" | "later";
            /** Format: date */
            date: string;
            /** Format: date-time */
            starts_at: string;
            ends_at: string | null;
            /** @enum {string} */
            window_label: "morning" | "afternoon" | "evening";
            type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            /** @description A consultation and fit in one visit: the first fit's steps, with the client's choice of product, or none, at the piece step. */
            one_visit: boolean;
            /** @description On a first fit, the hair system the client was sold, by its name in the console. Null on any other visit, on a one visit until the client chooses, and on a first fit that names none. */
            product: string | null;
            /** @description The area, never the street: the one the visit's pincode is in, from the service area; else the address's locality, or the city. */
            sector: string | null;
            /** @enum {string} */
            status: "scheduled" | "dispatched" | "in_progress" | "completed" | "cancelled" | "terminated" | "other";
            /**
             * @description Free for a visit the price book charges nothing for; at_visit for a one visit, paid for once the client is fitted. No response to a technician carries an amount.
             * @enum {string}
             */
            badge: "prepaid" | "credit" | "free" | "at_visit";
            /** @description How much of the day the visit takes: 1, 1.5 or 2 slots. Null for an unknown type. */
            slots: number | null;
            unlocked: boolean;
            /** Format: date-time */
            unlocks_at: string;
            /** @description Null until the day before the visit; the API enforces it, not the screen. */
            address: {
                line1: string;
                line2: string | null;
                building: string | null;
                tower: string | null;
                floor: string | null;
                flat: string | null;
                landmark: string | null;
                locality: string;
                city: string;
                pincode: string;
                lat: number | null;
                lng: number | null;
            } | null;
            access_notes: string | null;
            /** @description Null until the day before the visit. */
            client: {
                name: string;
                mobile: string;
                note: string | null;
            } | null;
            progress: components["schemas"]["TechnicianJobProgress"];
            /** @description How long this visit's type waits before a no-show may be closed, so a phone with no signal can count it. */
            no_show_wait_min: number;
            /** @description The client's pieces, newest fit first. Null until the day before the visit. */
            pieces: components["schemas"]["Piece"][] | null;
            /** @description The client's latest earlier visit with after photographs; null for a first visit. */
            last_visit: {
                /** Format: date */
                date: string;
                /** @description The first name of who did it. */
                technician: string | null;
                /** @description Its after photograph, never to be kept on the phone. */
                photo_url: string;
            } | null;
            /** @description The day-before or arrival WhatsApp to the client, and when it was delivered. */
            reminder: {
                delivered_at: string | null;
            } | null;
            /** @description The steps this visit type runs, in order; a consultation's and a one visit's take the profile. */
            steps: ("check_in" | "start" | "before_photos" | "checklist" | "consumables" | "piece" | "after_photos" | "outcome" | "profile")[];
            /** @description This kind of visit's checklist, as ops set it in the console, in its order. */
            checklist: components["schemas"]["JobSheetItem"][];
            /** @description The reasons a job may be left partly done, as ops set them, in their order. */
            partial_reasons: components["schemas"]["JobSheetItem"][];
            /** @description Every consumable the technician may record, those this job's service is expected to use first, each with the count its stepper starts at. */
            consumables: components["schemas"]["TechnicianConsumable"][];
            /** @description On a one visit and a consultation, the products by name and never by price: the first fit's services offered on the visit's day, in ops' order, which a one visit's client chooses from and the profile names. Empty for any other visit. */
            products: components["schemas"]["TechnicianProduct"][];
            /** @description On a one visit closed as done with the client fitted, its payment link; else null. */
            payment_link: {
                /** @description The link Razorpay texted the client, to show them; null until Razorpay has made it. */
                url: string | null;
                paid: boolean;
            } | null;
            /** @description On a one visit, the discount code already on it, so the outcome step asks for none; never what it takes off. Null on any other visit, and on a one visit with no code. */
            discount_code: {
                code: string;
                /**
                 * @description client: as they booked; ops: on the booking in the console; technician: at the visit.
                 * @enum {string}
                 */
                given_by: "client" | "technician" | "ops";
            } | null;
            /** @description The client's hair profile as it stands, for the piece card and for the profile step to start from. Null until the day before the visit, or before one is recorded. */
            profile: components["schemas"]["HairProfile"] | null;
        };
        TechnicianJobProgress: {
            checked_in_at: string | null;
            /** @description When the job may close as a no-show, from the check-in we hold; null before one landed. */
            wait_ends_at: string | null;
            /** @description How far from the address that check-in was; null when nothing could be measured. */
            distance_m: number | null;
            started_at: string | null;
            /** @description The steps that have reached us, in that order: the job's events, and the profile once recorded. */
            steps_done: ("check_in" | "start" | "before_photos" | "checklist" | "consumables" | "piece" | "after_photos" | "outcome" | "profile")[];
            outcome: string | null;
        };
        Piece: {
            piece_code: string;
            base: string | null;
            supplier_lot: string | null;
            fitted_at: string | null;
            replacement_due_at: string | null;
            failed_at: string | null;
            failure_reason: string | null;
        };
        JobSheetItem: {
            id: string;
            label: string;
        };
        TechnicianConsumable: {
            /** @description What the consumables step sends back. */
            code: string;
            name: string;
            /** @description What one is counted in: strip, ml, sachet. */
            unit: string;
            /** @description How many this job's service is expected to use; 0 for one it lists no use for. */
            expected: number;
        };
        TechnicianProduct: {
            /** @description What the piece step sends back as product. */
            tier: string;
            name: string;
        };
        HairProfile: {
            /**
             * Format: uuid
             * @description The version's own ID, which a write names as based_on.
             */
            id: string;
            /** Format: date-time */
            recorded_at: string;
            fit: components["schemas"]["HairFitSpecRead"];
            /** @description Null where none was recorded. */
            history: components["schemas"]["HairHistory"] | null;
        };
        /** @description Every field is sent, null where it was not taken. */
        HairFitSpecRead: {
            /** @enum {string|null} */
            norwood_stage: "I" | "II" | "III" | "IV" | "V" | "VI" | "VII" | null;
            /** @description In centimetres, 40 to 70, to one decimal. */
            head_circumference_cm: number | null;
            /** @description In centimetres, 20 to 50, to one decimal. */
            front_to_nape_cm: number | null;
            /** @description In centimetres, over the top, 20 to 50, to one decimal. */
            ear_to_ear_cm: number | null;
            /** @description In centimetres, 20 to 50, to one decimal. */
            temple_to_temple_cm: number | null;
            /** @description In inches, 2 to 12, to one decimal. */
            base_width_in: number | null;
            /** @description In inches, 2 to 14, to one decimal. */
            base_length_in: number | null;
            /**
             * @description The suppliers' colour code, #1B written 1B.
             * @enum {string|null}
             */
            colour: "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "1B" | null;
            grey_percent: number | null;
            /** @description In per cent. */
            density_percent: 80 | 100 | 120 | 140 | null;
            /** @enum {string|null} */
            wave: "straight" | "slight_wave" | "wavy" | "curly" | null;
            /** @enum {string|null} */
            hairline: "natural" | "receded" | "straight" | "widows_peak" | null;
            /** @description The product, by the tier of its first-fit service: one the services table holds, retired or not. */
            product: string | null;
            /**
             * @description Tape, glue, or both.
             * @enum {string|null}
             */
            attachment: "tape" | "glue" | "both" | null;
            /** @description The product's name, never its price. */
            product_name: string | null;
        };
        /** @description Every field is sent, null where it was not taken. */
        HairFitSpec: {
            /** @enum {string|null} */
            norwood_stage: "I" | "II" | "III" | "IV" | "V" | "VI" | "VII" | null;
            /** @description In centimetres, 40 to 70, to one decimal. */
            head_circumference_cm: number | null;
            /** @description In centimetres, 20 to 50, to one decimal. */
            front_to_nape_cm: number | null;
            /** @description In centimetres, over the top, 20 to 50, to one decimal. */
            ear_to_ear_cm: number | null;
            /** @description In centimetres, 20 to 50, to one decimal. */
            temple_to_temple_cm: number | null;
            /** @description In inches, 2 to 12, to one decimal. */
            base_width_in: number | null;
            /** @description In inches, 2 to 14, to one decimal. */
            base_length_in: number | null;
            /**
             * @description The suppliers' colour code, #1B written 1B.
             * @enum {string|null}
             */
            colour: "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "1B" | null;
            grey_percent: number | null;
            /** @description In per cent. */
            density_percent: 80 | 100 | 120 | 140 | null;
            /** @enum {string|null} */
            wave: "straight" | "slight_wave" | "wavy" | "curly" | null;
            /** @enum {string|null} */
            hairline: "natural" | "receded" | "straight" | "widows_peak" | null;
            /** @description The product, by the tier of its first-fit service: one the services table holds, retired or not. */
            product: string | null;
            /**
             * @description Tape, glue, or both.
             * @enum {string|null}
             */
            attachment: "tape" | "glue" | "both" | null;
        };
        /** @description Health information the client told us: our records alone, never Zoho or a log. */
        HairHistory: {
            /** @description Every remedy the client has tried, each once; none, said alone, for none. Empty: not answered. */
            remedies: ("none" | "minoxidil" | "finasteride" | "transplant" | "other_systems" | "other")[];
            /** @description With a transplant only, and no later than this year. */
            transplant_year: number | null;
            skin_and_allergies: string | null;
        };
        CheckIn: {
            passed: boolean;
            /** @description Null when the address has no coordinates, so nothing could be measured. */
            distance_m: number | null;
            radius_m: number;
            /** Format: date-time */
            checked_in_at: string;
            /** @description When the job may be closed as a no-show; null when the check-in failed. */
            wait_ends_at: string | null;
            accepted: components["schemas"]["TechnicianWriteAccepted"] | null;
        };
        TechnicianWriteAccepted: {
            event_id: string;
            /** @description True when this write had already landed. */
            replayed: boolean;
            /** @enum {string} */
            fsm_write_state: "pending" | "written" | "rejected";
            progress: components["schemas"]["TechnicianJobProgress"];
        };
        CheckInRequest: {
            lat: number;
            lng: number;
            accuracy_m?: number | null;
            /**
             * Format: date-time
             * @description The phone's clock, kept within bounds and never later than we received it; left out, the event ID's time, else ours.
             */
            at?: string;
        };
        TechnicianPhotoUrl: {
            /** @description A path on this host. PUT the photograph there. */
            upload_url: string;
            /** @description A path on this host. PUT the photograph's small copy there, once the photograph is in. */
            small_upload_url: string;
            /** Format: date-time */
            expires_at: string;
        };
        TechnicianPhotoUrlRequest: {
            /** @enum {string} */
            phase: "before" | "after";
            /** @enum {string} */
            angle: "front" | "top" | "left" | "right" | "hair";
        };
        TechnicianPhotoTaken: {
            /**
             * Format: uuid
             * @description This upload of the angle's photograph, which its small copy's upload names.
             */
            take: string;
        };
        TechnicianPhotosRequest: {
            /** @enum {string} */
            phase: "before" | "after";
        };
        ChecklistRequest: {
            done: string[];
        };
        /** @description What was used, each by the code the job's card gave it. None used is an empty list. A code the catalogue does not hold is refused, fields items. */
        ConsumablesRequest: {
            items: ({
                code: string;
                quantity: number;
            } | {
                name: string;
                quantity: number;
            })[];
        };
        PieceRequest: components["schemas"]["PieceFitted"] | components["schemas"]["PieceDeclined"];
        /** @description The piece fitted, with its base and lot, and on a replacement the one that came off. A failure_reason on the piece itself marks it as failed and fits nothing. */
        PieceFitted: {
            piece_code: string;
            base?: string | null;
            supplier_lot?: string | null;
            failure_reason?: string | null;
            /** @description On a replacement: the piece that came off, and why it failed. */
            old_piece?: {
                piece_code: string;
                failure_reason: string;
            } | null;
            /** @description On a one visit, and only there: the product the client chose, by its tier from the card's products. */
            product?: string;
        };
        /** @description On a one visit, and only there: the client decided against the fit, so nothing was fitted, and closing the visit as done makes it a consultation. */
        PieceDeclined: {
            /** @enum {boolean} */
            declined: true;
        };
        /** @description Kept in our records alone: nothing of it goes to FSM. */
        TechnicianProfileRecorded: {
            event_id: string;
            /** @description True when this write had already landed. */
            replayed: boolean;
            progress: components["schemas"]["TechnicianJobProgress"];
        };
        /** @description The client's whole profile as it stands now: the card's latest, changed where the technician changed it. Each is a new version. */
        TechnicianProfileRequest: {
            fit: components["schemas"]["HairFitSpec"];
            history: components["schemas"]["HairHistory"] | null;
            /** @description The id of the version the form started from: the latest as it was read; null where there was none. */
            based_on: string | null;
        };
        OutcomeRequest: {
            /** @enum {string} */
            outcome: "done";
        } | {
            /** @enum {string} */
            outcome: "partial";
            /** @description One of the card's partial_reasons, by its id; one ops have since taken off is still taken. */
            reason: string;
        };
        NoShowClose: {
            closed: boolean;
            /** Format: date-time */
            wait_ends_at: string;
            case_id: string | null;
            accepted: components["schemas"]["TechnicianWriteAccepted"] | null;
        };
        /** @description Whether the label is one of the job's client's pieces. */
        PieceLookup: {
            piece: components["schemas"]["Piece"];
            belongs_to_this_job: boolean;
        };
        TechnicianDiscountCodeApplied: {
            /** @description The code, as it is kept: in capitals. */
            code: string;
        };
        TechnicianDiscountCode: {
            /** @description As the client gave it, any case. */
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
