/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment, version and database reachability */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                /** @description The database is unreachable or belongs to another environment */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a login code on WhatsApp. The answer is the same whether or not FSM lists the number */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianLoginRequest"];
                };
            };
            responses: {
                /** @description A code is on its way, if FSM lists this number */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianChallenge"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description rate_limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy: today's ceiling on codes is reached */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check a code. The right one opens a session on this phone (the mm_tech cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianVerifyRequest"];
                };
            };
            responses: {
                /** @description Right, with a session; or wrong, with the attempts left */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianVerify"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description code_expired: expired, used, or void after five wrong codes */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session on this phone */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in, and the phone this session is bound to */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The signed-in technician */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianMe"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The technician's jobs on a date. Today and tomorrow in full; later dates only time, type and sector */
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The day's jobs, in time order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianJobs"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of the technician's jobs, with the day-before unlock enforced */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianJobDetail"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job of this technician's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** I have arrived: the time and the phone's position, inside the geofence */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-client-event-id": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckInRequest"];
                };
            };
            responses: {
                /** @description Pass or fail, with the distance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckIn"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the job. The duration runs from here to the outcome */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-client-event-id": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/photos/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A link to PUT one photograph to, for one phase and angle */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianPhotoUrlRequest"];
                };
            };
            responses: {
                /** @description The link, good for fifteen minutes */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianPhotoUrl"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/photos/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** The photograph itself: a JPEG or PNG, at most 12 MB */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Received */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: the link is wrong or expired */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_invalid_file: not a JPEG or PNG, or over 12 MB */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The phase's five photographs are in; attach them to FSM */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-client-event-id": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianPhotosRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The service checklist, per visit type */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-client-event-id": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChecklistRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/consumables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consumables used, with quantities */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-client-event-id": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConsumablesRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/piece": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The piece: a replacement's and a first fit's step only */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-client-event-id": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PieceRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Done, or partial with a reason */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-client-event-id": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OutcomeRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/no-show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close the job as a no-show, once the wait has run */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-client-event-id": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Closed, with the case ops will rule on */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoShowClose"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description too_early_to_close: the wait has not run out */
                425: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/pieces/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The piece a label names */
        get: {
            parameters: {
                query: {
                    code: string;
                    job?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The piece */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PieceLookup"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no piece with that label */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "not_found" | "invalid_request" | "turnstile_failed" | "rate_limited" | "idempotency_in_progress" | "idempotency_key_reused" | "environment_mismatch" | "unavailable" | "internal_error" | "busy" | "photo_invalid_file" | "upload_already_received" | "upload_missing" | "session_required" | "job_not_claimable" | "look_limit_reached" | "unauthorized" | "forbidden_origin" | "access_required" | "code_expired" | "too_early" | "number_in_use" | "not_ready" | "ops_assisted" | "taken" | "not_bookable" | "hold_expired" | "not_changeable" | "terms_changed" | "consent_required" | "device_revoked" | "superseded" | "out_of_order" | "clash" | "fsm_refused" | "too_early_to_close" | "no_service_area";
                request_id: string;
                /** @description invalid_request only: the fields that failed validation, never their values. */
                fields?: string[];
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @enum {string} */
            environment: "local" | "staging" | "production";
            /** @description Cloudflare Worker version ID serving this request. */
            version_id: string;
            /** @description Tag given at upload: the git commit SHA in remote environments. */
            version_tag: string | null;
            /**
             * @description ok: reachable and marked as this environment's database. unmarked: no identity row. mismatch: marked as another environment's database.
             * @enum {string}
             */
            d1: "ok" | "unmarked" | "mismatch" | "unreachable";
        };
        TechnicianChallenge: {
            /** Format: uuid */
            challenge_id: string;
            expires_in_s: number;
        };
        TechnicianLoginRequest: {
            mobile: string;
            /** @description The app's own ID for this phone, kept in its storage. */
            device_id: string;
        };
        TechnicianVerify: {
            /** @enum {boolean} */
            verified: true;
            first_name: string;
            device_id: string;
        } | {
            /** @enum {boolean} */
            verified: false;
            attempts_left: number;
        };
        TechnicianVerifyRequest: {
            /** Format: uuid */
            challenge_id: string;
            code: string;
            /** @description The app's own ID for this phone, kept in its storage. */
            device_id: string;
        };
        TechnicianMe: {
            name: string;
            first_name: string;
            /** @description For the chip at the head of Today: the first and last initials. */
            initials: string;
            device: {
                /** @description The phone's own ID, as it sent it at sign-in. */
                device_id: string;
                /** @description Ours, from the User-Agent at sign-in. */
                label: string | null;
                /** Format: date-time */
                enrolled_at: string;
            };
        };
        /** @description Jobs further out carry only time, type and sector. */
        TechnicianJobs: {
            /** Format: date */
            date: string;
            jobs: components["schemas"]["TechnicianJob"][];
        };
        TechnicianJob: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            day: "today" | "tomorrow" | "later";
            /** Format: date */
            date: string;
            /** Format: date-time */
            starts_at: string;
            ends_at: string | null;
            /** @enum {string} */
            window_label: "morning" | "afternoon" | "evening";
            type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            /** @description The area, never the street. */
            sector: string | null;
            /** @enum {string} */
            status: "scheduled" | "dispatched" | "in_progress" | "completed" | "cancelled" | "terminated" | "other";
            /**
             * @description No response to a technician carries an amount.
             * @enum {string}
             */
            badge: "prepaid" | "credit";
            unlocked: boolean;
            /** Format: date-time */
            unlocks_at: string;
        };
        TechnicianJobDetail: components["schemas"]["TechnicianJob"] & {
            /** @description Null until the day before the visit; the API enforces it, not the screen. */
            address: {
                line1: string;
                line2: string | null;
                locality: string;
                city: string;
                pincode: string;
                lat: number | null;
                lng: number | null;
            } | null;
            access_notes: string | null;
            /** @description Null until the day before the visit. */
            client: {
                name: string;
                mobile: string;
                note: string | null;
            } | null;
            progress: components["schemas"]["TechnicianJobProgress"];
            /** @description The steps this visit type runs, in order. */
            steps: ("check_in" | "start" | "before_photos" | "checklist" | "consumables" | "piece" | "after_photos" | "outcome")[];
            checklist: {
                id: string;
                label: string;
            }[];
            partial_reasons: ("client_stopped_it" | "piece_not_ready" | "client_unwell" | "more_time_needed")[];
        };
        TechnicianJobProgress: {
            checked_in_at: string | null;
            started_at: string | null;
            steps_done: ("check_in" | "start" | "before_photos" | "checklist" | "consumables" | "piece" | "after_photos" | "outcome")[];
            outcome: string | null;
        };
        CheckIn: {
            passed: boolean;
            /** @description Null when the address has no coordinates, so nothing could be measured. */
            distance_m: number | null;
            radius_m: number;
            /** Format: date-time */
            checked_in_at: string;
            /** @description When the job may be closed as a no-show; null when the check-in failed. */
            wait_ends_at: string | null;
            accepted: components["schemas"]["TechnicianWriteAccepted"] | null;
        };
        TechnicianWriteAccepted: {
            event_id: string;
            /** @description True when this write had already landed. */
            replayed: boolean;
            /** @enum {string} */
            fsm_write_state: "pending" | "written" | "rejected";
            progress: components["schemas"]["TechnicianJobProgress"];
        };
        CheckInRequest: {
            lat: number;
            lng: number;
            accuracy_m?: number | null;
            /**
             * Format: date-time
             * @description The phone's clock; ours is used when it is left out.
             */
            at?: string;
        };
        TechnicianPhotoUrl: {
            /** @description A path on this host. PUT the photograph there. */
            upload_url: string;
            /** Format: date-time */
            expires_at: string;
        };
        TechnicianPhotoUrlRequest: {
            /** @enum {string} */
            phase: "before" | "after";
            /** @enum {string} */
            angle: "front" | "top" | "left" | "right" | "hair";
        };
        TechnicianPhotosRequest: {
            /** @enum {string} */
            phase: "before" | "after";
        };
        ChecklistRequest: {
            done: string[];
        };
        ConsumablesRequest: {
            items: {
                name: string;
                quantity: number;
            }[];
        };
        /** @description A failure_reason marks the piece that came off as failed. */
        PieceRequest: {
            piece_code: string;
            base?: string | null;
            supplier_lot?: string | null;
            failure_reason?: string | null;
        };
        OutcomeRequest: {
            /** @enum {string} */
            outcome: "done";
        } | {
            /** @enum {string} */
            outcome: "partial";
            /** @enum {string} */
            reason: "client_stopped_it" | "piece_not_ready" | "client_unwell" | "more_time_needed";
        };
        NoShowClose: {
            closed: boolean;
            /** Format: date-time */
            wait_ends_at: string;
            case_id: string | null;
            accepted: components["schemas"]["TechnicianWriteAccepted"] | null;
        };
        /** @description Whether the label is one of the job's client's pieces. */
        PieceLookup: {
            piece: components["schemas"]["Piece"];
            belongs_to_this_job: boolean;
        };
        Piece: {
            piece_code: string;
            base: string | null;
            supplier_lot: string | null;
            fitted_at: string | null;
            replacement_due_at: string | null;
            failed_at: string | null;
            failure_reason: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
