/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment, version and database reachability */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                /** @description The database is unreachable or belongs to another environment */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a login code on WhatsApp. The answer is the same whether or not FSM lists the number */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianLoginRequest"];
                };
            };
            responses: {
                /** @description A code is on its way, if FSM lists this number */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianChallenge"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description rate_limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy: today's ceiling on codes is reached */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check a code. The right one opens a session on this phone (the mm_tech cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianVerifyRequest"];
                };
            };
            responses: {
                /** @description Right, with a session; or wrong, with the attempts left */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianVerify"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description code_expired: expired, used, or void after five wrong codes */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session on this phone */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description session_required; device_revoked: there was no session here to end */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in, and the phone this session is bound to */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The signed-in technician */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianMe"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The technician's jobs on a date. Today and tomorrow in full; later dates only time, type and sector */
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The day's jobs, in time order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianJobs"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of the technician's jobs, with the day-before unlock enforced */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianJobDetail"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job of this technician's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/last-visit-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The client's last visit, after: one photograph, under the card's own unlock, never cached */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                        "image/png": string;
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job of this technician's, not unlocked yet, or no earlier visit's photograph */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** I have arrived: the time and the phone's position, inside the geofence */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckInRequest"];
                };
            };
            responses: {
                /** @description Pass or fail, with the distance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckIn"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first; not_today: the job is on another day */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the job. The duration runs from here to the outcome */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first; not_today: the job is on another day */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/photos/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A link to PUT one photograph to, for one phase and angle */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianPhotoUrlRequest"];
                };
            };
            responses: {
                /** @description The link, good for fifteen minutes */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianPhotoUrl"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job, or never this technician's */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: the job was given to another technician or cancelled while its photographs waited; moved names whom */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/photos/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** The photograph itself: a JPEG or PNG, at most 2 MB */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Received */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianPhotoTaken"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: the link is wrong or expired */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_invalid_file: not a JPEG or PNG, or over 2 MB */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy: R2 holds past the runaway ceiling; the phone keeps the photograph and sends it later */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/photos/{token}/small": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** The photograph's small copy, for the client app's rows: a JPEG of at most 64 KB and 800 px a side */
        put: {
            parameters: {
                query: {
                    /** @description The take the photograph's upload answered. */
                    take: string;
                };
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Received, or held already */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: the link is wrong or expired */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description upload_missing: that take is not the angle's photograph: not arrived yet, or taken again since */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_invalid_file: not a JPEG, or over 64 KB or 800 px a side */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description busy: R2 holds past the runaway ceiling */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The phase's five photographs are in; attach them to FSM */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianPhotosRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The service checklist, per visit type */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChecklistRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/consumables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consumables used, with quantities */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConsumablesRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/piece": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The piece: a replacement's and a first fit's step only */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PieceRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Done, or partial with a reason */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OutcomeRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWriteAccepted"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/jobs/{id}/no-show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close the job as a no-show, once the wait has run */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description The phone's own ID for this write; a replay of it changes nothing. A UUIDv7 carries the moment it was queued. */
                    "x-client-event-id": string;
                    /** @description The job's starts_at as the phone holds it. When ops have moved the job since, the write is superseded, field time. */
                    "x-job-starts-at"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Closed, with the case ops will rule on */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoShowClose"];
                    };
                };
                /** @description invalid_request: see error.fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description session_required; device_revoked: ops revoked this phone, so drop the cached jobs */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no such job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description superseded: FSM moved the job; out_of_order: send the step before this one first; already_started: the job was started, so the client was home */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description too_early_to_close: the wait has not run out */
                425: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech/pieces/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The piece a label names */
        get: {
            parameters: {
                query: {
                    code: string;
                    job?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The piece */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PieceLookup"];
                    };
                };
                /** @description session_required; device_revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description not_found: no piece with that label */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "not_found" | "invalid_request" | "turnstile_failed" | "rate_limited" | "idempotency_in_progress" | "idempotency_key_reused" | "environment_mismatch" | "unavailable" | "internal_error" | "busy" | "photo_invalid_file" | "upload_already_received" | "upload_missing" | "session_required" | "job_not_claimable" | "look_limit_reached" | "claim_required" | "whatsapp_unavailable" | "unauthorized" | "visit_booked" | "payment_held" | "forbidden_origin" | "access_required" | "code_expired" | "too_early" | "number_in_use" | "not_ready" | "ops_assisted" | "taken" | "not_bookable" | "hold_expired" | "address_required" | "already_booked" | "not_changeable" | "terms_changed" | "consent_required" | "device_revoked" | "superseded" | "out_of_order" | "not_today" | "already_started" | "clash" | "on_leave" | "does_not_fit" | "fsm_refused" | "fsm_partly" | "too_early_to_close" | "no_service_area" | "service_exists" | "last_of_kind" | "service_retired" | "unknown_invite" | "own_invite" | "already_invited" | "already_fitted" | "already_disputed" | "not_disputable";
                request_id: string;
                /** @description invalid_request: the fields that failed validation, never their values; superseded: what changed under the caller. */
                fields?: string[];
                /** @description superseded, to a technician's phone, for a job given to another technician: whom, and when (docs/open-points.md, item 92). */
                moved?: {
                    /** @description Their first name, and nothing else of theirs */
                    technician: string;
                    /** @description When ops moved the job to them; null when it was moved in FSM itself */
                    at: string | null;
                };
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @enum {string} */
            environment: "local" | "staging" | "production";
            /** @description Cloudflare Worker version ID serving this request. */
            version_id: string;
            /** @description Tag given at upload: the git commit SHA in remote environments. */
            version_tag: string | null;
            /**
             * @description ok: reachable and marked as this environment's database. unmarked: no identity row. mismatch: marked as another environment's database.
             * @enum {string}
             */
            d1: "ok" | "unmarked" | "mismatch" | "unreachable";
        };
        TechnicianChallenge: {
            /** Format: uuid */
            challenge_id: string;
            expires_in_s: number;
        };
        TechnicianLoginRequest: {
            mobile: string;
            /** @description The app's own ID for this phone, kept in its storage. */
            device_id: string;
        };
        TechnicianVerify: {
            /** @enum {boolean} */
            verified: true;
            first_name: string;
            device_id: string;
        } | {
            /** @enum {boolean} */
            verified: false;
            attempts_left: number;
        };
        TechnicianVerifyRequest: {
            /** Format: uuid */
            challenge_id: string;
            code: string;
            /** @description The app's own ID for this phone, kept in its storage. */
            device_id: string;
        };
        TechnicianMe: {
            name: string;
            first_name: string;
            /** @description For the chip at the head of Today: the first and last initials. */
            initials: string;
            device: {
                /** @description The phone's own ID, as it sent it at sign-in. */
                device_id: string;
                /** @description Ours, from the User-Agent at sign-in. */
                label: string | null;
                /** Format: date-time */
                enrolled_at: string;
            };
        };
        /** @description Jobs further out carry only time, type and sector. */
        TechnicianJobs: {
            /** Format: date */
            date: string;
            jobs: components["schemas"]["TechnicianJob"][];
        };
        TechnicianJob: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            day: "today" | "tomorrow" | "later";
            /** Format: date */
            date: string;
            /** Format: date-time */
            starts_at: string;
            ends_at: string | null;
            /** @enum {string} */
            window_label: "morning" | "afternoon" | "evening";
            type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            /** @description The area, never the street: the one the visit's pincode is in, from the service area; else the address's locality, or the city. */
            sector: string | null;
            /** @enum {string} */
            status: "scheduled" | "dispatched" | "in_progress" | "completed" | "cancelled" | "terminated" | "other";
            /**
             * @description Free for a visit the price book charges nothing for. No response to a technician carries an amount.
             * @enum {string}
             */
            badge: "prepaid" | "credit" | "free";
            /** @description How much of the day the visit takes: 1, 1.5 or 2 slots. Null for an unknown type. */
            slots: number | null;
            unlocked: boolean;
            /** Format: date-time */
            unlocks_at: string;
        };
        TechnicianJobDetail: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            day: "today" | "tomorrow" | "later";
            /** Format: date */
            date: string;
            /** Format: date-time */
            starts_at: string;
            ends_at: string | null;
            /** @enum {string} */
            window_label: "morning" | "afternoon" | "evening";
            type: ("consultation" | "first_fit" | "service" | "replacement") | null;
            /** @description The area, never the street: the one the visit's pincode is in, from the service area; else the address's locality, or the city. */
            sector: string | null;
            /** @enum {string} */
            status: "scheduled" | "dispatched" | "in_progress" | "completed" | "cancelled" | "terminated" | "other";
            /**
             * @description Free for a visit the price book charges nothing for. No response to a technician carries an amount.
             * @enum {string}
             */
            badge: "prepaid" | "credit" | "free";
            /** @description How much of the day the visit takes: 1, 1.5 or 2 slots. Null for an unknown type. */
            slots: number | null;
            unlocked: boolean;
            /** Format: date-time */
            unlocks_at: string;
            /** @description Null until the day before the visit; the API enforces it, not the screen. */
            address: {
                line1: string;
                line2: string | null;
                building: string | null;
                tower: string | null;
                floor: string | null;
                flat: string | null;
                landmark: string | null;
                locality: string;
                city: string;
                pincode: string;
                lat: number | null;
                lng: number | null;
            } | null;
            access_notes: string | null;
            /** @description Null until the day before the visit. */
            client: {
                name: string;
                mobile: string;
                note: string | null;
            } | null;
            progress: components["schemas"]["TechnicianJobProgress"];
            /** @description How long this visit's type waits before a no-show may be closed, so a phone with no signal can count it. */
            no_show_wait_min: number;
            /** @description The client's pieces, newest fit first. Null until the day before the visit. */
            pieces: components["schemas"]["Piece"][] | null;
            /** @description The client's latest earlier visit with after photographs; null for a first visit. */
            last_visit: {
                /** Format: date */
                date: string;
                /** @description The first name of who did it. */
                technician: string | null;
                /** @description Its after photograph, never to be kept on the phone. */
                photo_url: string;
            } | null;
            /** @description The day-before or arrival WhatsApp to the client, and when it was delivered. */
            reminder: {
                delivered_at: string | null;
            } | null;
            /** @description The steps this visit type runs, in order. */
            steps: ("check_in" | "start" | "before_photos" | "checklist" | "consumables" | "piece" | "after_photos" | "outcome")[];
            /** @description This kind of visit's checklist, as ops set it in the console, in its order. */
            checklist: components["schemas"]["JobSheetItem"][];
            /** @description The reasons a job may be left partly done, as ops set them, in their order. */
            partial_reasons: components["schemas"]["JobSheetItem"][];
            /** @description Every consumable the technician may record, those this job's service is expected to use first, each with the count its stepper starts at. */
            consumables: components["schemas"]["TechnicianConsumable"][];
        };
        TechnicianJobProgress: {
            checked_in_at: string | null;
            /** @description When the job may close as a no-show, from the check-in we hold; null before one landed. */
            wait_ends_at: string | null;
            /** @description How far from the address that check-in was; null when nothing could be measured. */
            distance_m: number | null;
            started_at: string | null;
            steps_done: ("check_in" | "start" | "before_photos" | "checklist" | "consumables" | "piece" | "after_photos" | "outcome")[];
            outcome: string | null;
        };
        Piece: {
            piece_code: string;
            base: string | null;
            supplier_lot: string | null;
            fitted_at: string | null;
            replacement_due_at: string | null;
            failed_at: string | null;
            failure_reason: string | null;
        };
        JobSheetItem: {
            id: string;
            label: string;
        };
        TechnicianConsumable: {
            /** @description What the consumables step sends back. */
            code: string;
            name: string;
            /** @description What one is counted in: strip, ml, sachet. */
            unit: string;
            /** @description How many this job's service is expected to use; 0 for one it lists no use for. */
            expected: number;
        };
        CheckIn: {
            passed: boolean;
            /** @description Null when the address has no coordinates, so nothing could be measured. */
            distance_m: number | null;
            radius_m: number;
            /** Format: date-time */
            checked_in_at: string;
            /** @description When the job may be closed as a no-show; null when the check-in failed. */
            wait_ends_at: string | null;
            accepted: components["schemas"]["TechnicianWriteAccepted"] | null;
        };
        TechnicianWriteAccepted: {
            event_id: string;
            /** @description True when this write had already landed. */
            replayed: boolean;
            /** @enum {string} */
            fsm_write_state: "pending" | "written" | "rejected";
            progress: components["schemas"]["TechnicianJobProgress"];
        };
        CheckInRequest: {
            lat: number;
            lng: number;
            accuracy_m?: number | null;
            /**
             * Format: date-time
             * @description The phone's clock, kept within bounds and never later than we received it; left out, the event ID's time, else ours.
             */
            at?: string;
        };
        TechnicianPhotoUrl: {
            /** @description A path on this host. PUT the photograph there. */
            upload_url: string;
            /** @description A path on this host. PUT the photograph's small copy there, once the photograph is in. */
            small_upload_url: string;
            /** Format: date-time */
            expires_at: string;
        };
        TechnicianPhotoUrlRequest: {
            /** @enum {string} */
            phase: "before" | "after";
            /** @enum {string} */
            angle: "front" | "top" | "left" | "right" | "hair";
        };
        TechnicianPhotoTaken: {
            /**
             * Format: uuid
             * @description This upload of the angle's photograph, which its small copy's upload names.
             */
            take: string;
        };
        TechnicianPhotosRequest: {
            /** @enum {string} */
            phase: "before" | "after";
        };
        ChecklistRequest: {
            done: string[];
        };
        /** @description What was used, each by the code the job's card gave it. None used is an empty list. A code the catalogue does not hold is refused, fields items. */
        ConsumablesRequest: {
            items: ({
                code: string;
                quantity: number;
            } | {
                name: string;
                quantity: number;
            })[];
        };
        /** @description The piece fitted, with its base and lot, and on a replacement the one that came off. A failure_reason on the piece itself marks it as failed and fits nothing. */
        PieceRequest: {
            piece_code: string;
            base?: string | null;
            supplier_lot?: string | null;
            failure_reason?: string | null;
            /** @description On a replacement: the piece that came off, and why it failed. */
            old_piece?: {
                piece_code: string;
                failure_reason: string;
            } | null;
        };
        OutcomeRequest: {
            /** @enum {string} */
            outcome: "done";
        } | {
            /** @enum {string} */
            outcome: "partial";
            /** @description One of the card's partial_reasons, by its id; one ops have since taken off is still taken. */
            reason: string;
        };
        NoShowClose: {
            closed: boolean;
            /** Format: date-time */
            wait_ends_at: string;
            case_id: string | null;
            accepted: components["schemas"]["TechnicianWriteAccepted"] | null;
        };
        /** @description Whether the label is one of the job's client's pieces. */
        PieceLookup: {
            piece: components["schemas"]["Piece"];
            belongs_to_this_job: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
