// The OpenAPI document and docs/api.md are generated from the zod route
// schemas, never written by hand. scripts/generate-openapi.ts writes them; the
// contract test fails when a committed copy is stale.

import { createApp } from "./app.ts";

export const OPENAPI_INFO = {
  title: "Mane Man API",
  version: "1",
  description: "mm-api, served at https://{host}/api/*. Every response carries an X-Request-Id header.",
} as const;

export type OpenApiDocument = ReturnType<ReturnType<typeof createApp>["getOpenAPI31Document"]>;

export function buildOpenApiDocument(): OpenApiDocument {
  const app = createApp({
    environment: "local",
    providers: { IMAGE_PROVIDER: "stub", CRM_PROVIDER: "stub", MESSAGING_PROVIDER: "stub" },
  });
  return app.getOpenAPI31Document({
    openapi: "3.1.0",
    info: OPENAPI_INFO,
    servers: [
      { url: "https://maneman.in", description: "production" },
      { url: "https://staging.maneman.in", description: "staging (Cloudflare Access)" },
    ],
  });
}

const METHODS = ["get", "post", "put", "patch", "delete"] as const;

export interface DocumentedResponse {
  readonly description: string;
  readonly jsonSchema: unknown;
}

/** `value[key]` if `value` is an object that has `key`, otherwise undefined. */
function property(value: unknown, key: string): unknown {
  if (typeof value !== "object" || value === null || !(key in value)) return undefined;
  return (value as Record<string, unknown>)[key];
}

/** The OpenAPI types describe responses loosely, so read one without trusting its shape. */
export function readResponse(response: unknown): DocumentedResponse {
  const description = property(response, "description");
  const jsonSchema = property(property(property(response, "content"), "application/json"), "schema");
  return { description: typeof description === "string" ? description : "", jsonSchema };
}

const json = (value: unknown): string => ["```json", JSON.stringify(value, null, 2), "```"].join("\n");

export function renderApiMarkdown(document: OpenApiDocument): string {
  const out: string[] = [
    "<!-- Generated by `npm run openapi` from the zod schemas in src/. Do not edit. -->",
    "",
    `# ${document.info.title}`,
    "",
    document.info.description ?? "",
    "",
    "Errors carry a stable code and the request ID, never a stack trace or provider message:",
    "",
    json({ error: { code: "not_found", request_id: "…" } }),
    "",
    "## Endpoints",
    "",
  ];
  for (const [path, item] of Object.entries(document.paths ?? {})) {
    for (const method of METHODS) {
      const operation = item[method];
      if (operation === undefined) continue;
      out.push(`### ${method.toUpperCase()} ${path}`, "", operation.summary ?? "", "");
      const body = operation.requestBody;
      if (body !== undefined && "content" in body) {
        out.push("Request body:", "", json(body.content["application/json"]?.schema ?? {}), "");
      }
      for (const [status, raw] of Object.entries(operation.responses ?? {}) as [string, unknown][]) {
        const response = readResponse(raw);
        out.push(`**${status}**: ${response.description}`, "");
        if (response.jsonSchema !== undefined) out.push(json(response.jsonSchema), "");
      }
    }
  }
  out.push("## Schemas", "");
  for (const [name, schema] of Object.entries(document.components?.schemas ?? {})) {
    out.push(`### ${name}`, "", json(schema), "");
  }
  return `${out.join("\n").trimEnd()}\n`;
}
