/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: ff6713ab2d1cc872e5bbfb6e4a404c7b)
interface __BaseEnv_Env {
	UPLOADS: R2Bucket;
	RESULTS: R2Bucket;
	DB: D1Database;
	RENDER_QUEUE: Queue;
	CRM_QUEUE: Queue;
	MESSAGE_QUEUE: Queue;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "staging" | "production" | "local";
	IMAGE_PROVIDER: "ailabtools" | "stub";
	CRM_PROVIDER: "zoho" | "stub";
	MESSAGING_PROVIDER: "bsp" | "stub";
}
declare namespace Cloudflare {
	interface StagingEnv {
		UPLOADS: R2Bucket;
		RESULTS: R2Bucket;
		DB: D1Database;
		RENDER_QUEUE: Queue;
		CRM_QUEUE: Queue;
		MESSAGE_QUEUE: Queue;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "staging";
		IMAGE_PROVIDER: "ailabtools";
		CRM_PROVIDER: "zoho";
		MESSAGING_PROVIDER: "bsp";
	}
	interface ProductionEnv {
		UPLOADS: R2Bucket;
		RESULTS: R2Bucket;
		DB: D1Database;
		RENDER_QUEUE: Queue;
		CRM_QUEUE: Queue;
		MESSAGE_QUEUE: Queue;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "production";
		IMAGE_PROVIDER: "ailabtools";
		CRM_PROVIDER: "zoho";
		MESSAGING_PROVIDER: "bsp";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "IMAGE_PROVIDER" | "CRM_PROVIDER" | "MESSAGING_PROVIDER">> {}
}
