/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false src/worker-configuration.d.ts` (hash: 2a446caea7e25d06b018fca861de91d5)
interface __BaseEnv_Env {
	UPLOADS: R2Bucket;
	RESULTS: R2Bucket;
	DB: D1Database;
	RENDER_QUEUE: Queue;
	CRM_QUEUE: Queue;
	MESSAGE_QUEUE: Queue;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "staging" | "production" | "local";
	TURNSTILE_ACCEPT_TEST_TOKEN: "true" | "false";
	IMAGE_PROVIDER: "ailabtools" | "stub";
	CRM_PROVIDER: "zoho" | "stub";
	MESSAGING_PROVIDER: "evolution" | "stub";
	ACCESS_PROVIDER: "cloudflare" | "stub";
	ACCESS_TEAM_DOMAIN: "summer-math-0275.cloudflareaccess.com";
	VISIT_LEAD_DAYS: "2";
	LEAD_MOBILE_DAILY_LIMIT: "5";
	LEAD_IP_DAILY_LIMIT: "20";
	TRYON_UPLOAD_IP_HOURLY_LIMIT: "5";
	TRYON_GENERATE_IP_HOURLY_LIMIT: "5";
	TRYON_CLAIM_MOBILE_DAILY_LIMIT: "3";
	RESULT_MESSAGE_MOBILE_DAILY_LIMIT: "3";
	RENDER_DAILY_CEILING: "20" | "40";
	UPLOAD_DAILY_CEILING: "40" | "80";
	RESULT_READ_DAILY_CEILING: "400" | "800";
	RESULT_RETENTION_DAYS: "3" | "30";
	UNKNOWN_COLOR_ROUTE: "pro_black";
	AILAB_CREDIT_FLOOR: "200";
	MESSAGING_ENABLED: "true" | "false";
	WA_RESULT_TEMPLATE: "tryon_result_v1";
	TURNSTILE_SECRET: string;
	IP_HASH_SALT: string;
	RESULT_SIGNING_KEY: string;
	ERASURE_SECRET: string;
	ALERT_WEBHOOK_URL: string;
	ZOHO_CLIENT_ID: string;
	ZOHO_CLIENT_SECRET: string;
	ZOHO_REFRESH_TOKEN: string;
	ZOHO_ACCOUNTS_HOST: string;
	ZOHO_API_HOST: string;
	ZOHO_LAR_ID: string;
	AILAB_API_KEY: string;
	EVOLUTION_API_URL: string;
	EVOLUTION_API_KEY: string;
	EVOLUTION_INSTANCE_NAME: string;
	MESSAGING_ALLOWLIST: string;
	LEAD_WEBHOOK_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface StagingEnv {
		UPLOADS: R2Bucket;
		RESULTS: R2Bucket;
		DB: D1Database;
		RENDER_QUEUE: Queue;
		CRM_QUEUE: Queue;
		MESSAGE_QUEUE: Queue;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "staging";
		TURNSTILE_ACCEPT_TEST_TOKEN: "true";
		IMAGE_PROVIDER: "ailabtools";
		CRM_PROVIDER: "zoho";
		MESSAGING_PROVIDER: "evolution";
		ACCESS_PROVIDER: "cloudflare";
		ACCESS_TEAM_DOMAIN: "summer-math-0275.cloudflareaccess.com";
		VISIT_LEAD_DAYS: "2";
		LEAD_MOBILE_DAILY_LIMIT: "5";
		LEAD_IP_DAILY_LIMIT: "20";
		TRYON_UPLOAD_IP_HOURLY_LIMIT: "5";
		TRYON_GENERATE_IP_HOURLY_LIMIT: "5";
		TRYON_CLAIM_MOBILE_DAILY_LIMIT: "3";
		RESULT_MESSAGE_MOBILE_DAILY_LIMIT: "3";
		RENDER_DAILY_CEILING: "20";
		UPLOAD_DAILY_CEILING: "40";
		RESULT_READ_DAILY_CEILING: "400";
		RESULT_RETENTION_DAYS: "3";
		UNKNOWN_COLOR_ROUTE: "pro_black";
		AILAB_CREDIT_FLOOR: "200";
		MESSAGING_ENABLED: "true";
		WA_RESULT_TEMPLATE: "tryon_result_v1";
		TURNSTILE_SECRET: string;
		IP_HASH_SALT: string;
		RESULT_SIGNING_KEY: string;
		ERASURE_SECRET: string;
		ALERT_WEBHOOK_URL: string;
		ZOHO_CLIENT_ID: string;
		ZOHO_CLIENT_SECRET: string;
		ZOHO_REFRESH_TOKEN: string;
		ZOHO_ACCOUNTS_HOST: string;
		ZOHO_API_HOST: string;
		ZOHO_LAR_ID: string;
		AILAB_API_KEY: string;
		EVOLUTION_API_URL: string;
		EVOLUTION_API_KEY: string;
		EVOLUTION_INSTANCE_NAME: string;
		MESSAGING_ALLOWLIST: string;
		LEAD_WEBHOOK_URL: string;
	}
	interface ProductionEnv {
		UPLOADS: R2Bucket;
		RESULTS: R2Bucket;
		DB: D1Database;
		RENDER_QUEUE: Queue;
		CRM_QUEUE: Queue;
		MESSAGE_QUEUE: Queue;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "production";
		TURNSTILE_ACCEPT_TEST_TOKEN: "false";
		IMAGE_PROVIDER: "ailabtools";
		CRM_PROVIDER: "zoho";
		MESSAGING_PROVIDER: "evolution";
		ACCESS_PROVIDER: "cloudflare";
		ACCESS_TEAM_DOMAIN: "summer-math-0275.cloudflareaccess.com";
		VISIT_LEAD_DAYS: "2";
		LEAD_MOBILE_DAILY_LIMIT: "5";
		LEAD_IP_DAILY_LIMIT: "20";
		TRYON_UPLOAD_IP_HOURLY_LIMIT: "5";
		TRYON_GENERATE_IP_HOURLY_LIMIT: "5";
		TRYON_CLAIM_MOBILE_DAILY_LIMIT: "3";
		RESULT_MESSAGE_MOBILE_DAILY_LIMIT: "3";
		RENDER_DAILY_CEILING: "40";
		UPLOAD_DAILY_CEILING: "80";
		RESULT_READ_DAILY_CEILING: "800";
		RESULT_RETENTION_DAYS: "30";
		UNKNOWN_COLOR_ROUTE: "pro_black";
		AILAB_CREDIT_FLOOR: "200";
		MESSAGING_ENABLED: "false";
		WA_RESULT_TEMPLATE: "tryon_result_v1";
		TURNSTILE_SECRET: string;
		IP_HASH_SALT: string;
		RESULT_SIGNING_KEY: string;
		ERASURE_SECRET: string;
		ALERT_WEBHOOK_URL: string;
		ZOHO_CLIENT_ID: string;
		ZOHO_CLIENT_SECRET: string;
		ZOHO_REFRESH_TOKEN: string;
		ZOHO_ACCOUNTS_HOST: string;
		ZOHO_API_HOST: string;
		ZOHO_LAR_ID: string;
		AILAB_API_KEY: string;
		EVOLUTION_API_URL: string;
		EVOLUTION_API_KEY: string;
		EVOLUTION_INSTANCE_NAME: string;
		MESSAGING_ALLOWLIST: string;
		LEAD_WEBHOOK_URL: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "TURNSTILE_ACCEPT_TEST_TOKEN" | "IMAGE_PROVIDER" | "CRM_PROVIDER" | "MESSAGING_PROVIDER" | "ACCESS_PROVIDER" | "ACCESS_TEAM_DOMAIN" | "VISIT_LEAD_DAYS" | "LEAD_MOBILE_DAILY_LIMIT" | "LEAD_IP_DAILY_LIMIT" | "TRYON_UPLOAD_IP_HOURLY_LIMIT" | "TRYON_GENERATE_IP_HOURLY_LIMIT" | "TRYON_CLAIM_MOBILE_DAILY_LIMIT" | "RESULT_MESSAGE_MOBILE_DAILY_LIMIT" | "RENDER_DAILY_CEILING" | "UPLOAD_DAILY_CEILING" | "RESULT_READ_DAILY_CEILING" | "RESULT_RETENTION_DAYS" | "UNKNOWN_COLOR_ROUTE" | "AILAB_CREDIT_FLOOR" | "MESSAGING_ENABLED" | "WA_RESULT_TEMPLATE" | "TURNSTILE_SECRET" | "IP_HASH_SALT" | "RESULT_SIGNING_KEY" | "ERASURE_SECRET" | "ALERT_WEBHOOK_URL" | "ZOHO_CLIENT_ID" | "ZOHO_CLIENT_SECRET" | "ZOHO_REFRESH_TOKEN" | "ZOHO_ACCOUNTS_HOST" | "ZOHO_API_HOST" | "ZOHO_LAR_ID" | "AILAB_API_KEY" | "EVOLUTION_API_URL" | "EVOLUTION_API_KEY" | "EVOLUTION_INSTANCE_NAME" | "MESSAGING_ALLOWLIST" | "LEAD_WEBHOOK_URL">> {}
}
